// packages/s2-vue/src/components/sheets/chart-sheet.vue
<script lang="ts">
import { customMerge, type S2Options, type ThemeCfg } from '@antv/s2';
import { computed, defineComponent, toRefs } from 'vue';
import { useExpose } from '../../hooks/useExpose';
import type { BaseSheetInitEmits } from '../../interface';
import { initBaseSheetProps } from '../../utils/initPropAndEmits';
import BaseSheet from './base-sheet.vue';

/**
 * ChartSheet - 用于在单元格中渲染图表
 *
 * 注意：要使用 ChartDataCell 自定义单元格渲染图表，
 * 需要在使用组件时通过 options.dataCell 配置 ChartDataCell
 *
 * 示例: 在 options 中配置 dataCell 属性:
 * dataCell: (viewMeta, spreadsheet) => new ChartDataCell(viewMeta, spreadsheet)
 */
export default defineComponent({
  name: 'ChartSheet',
  props: initBaseSheetProps(),
  emits: [] as unknown as BaseSheetInitEmits,
  setup(props, ctx) {
    const s2Ref = useExpose(ctx.expose);
    const { options: chartOptions, themeCfg: customThemeCfg } = toRefs(props);

    const s2Options = computed<S2Options>(() => {
      const defaultOptions: Partial<S2Options> = {
        style: {
          rowCell: {
            width: 100,
          },
          dataCell: {
            width: 400,
            height: 400,
          },
        },
        tooltip: {
          enable: true,
        },
      };

      const options: Partial<S2Options> = {
        showDefaultHeaderActionIcon: false,
        interaction: {
          hoverFocus: false,
          brushSelection: {
            dataCell: false,
          },
        },
      };

      return customMerge<S2Options>(
        defaultOptions,
        chartOptions.value,
        options,
      );
    });

    const themeCfg = computed<ThemeCfg>(() => {
      const defaultTheme: ThemeCfg['theme'] = {
        dataCell: {
          cell: {
            interactionState: {
              hoverFocus: {
                borderOpacity: 0,
              },
              selected: {
                borderOpacity: 0,
              },
            },
          },
        },
      };

      return customMerge<ThemeCfg>(defaultTheme, customThemeCfg?.value);
    });

    return {
      s2Ref,
      s2Options,
      themeCfg,
    };
  },
  components: {
    BaseSheet,
  },
});
</script>

<template>
  <BaseSheet
    v-bind="$props"
    ref="s2Ref"
    :options="s2Options"
    :themeCfg="themeCfg"
  />
</template>

// packages/s2-react/src/components/sheets/chart-sheet/index.tsx
import { customMerge, type ThemeCfg } from '@antv/s2';
import React from 'react';
import { BaseSheet } from '../base-sheet';
import type { SheetComponentOptions, SheetComponentsProps } from '../interface';
import { ChartSheetDataCell } from './custom-cell';

export const ChartSheet: React.FC<SheetComponentsProps> = React.memo(
  (props) => {
    const {
      options: defaultOptions,
      themeCfg: defaultThemeCfg,
      ...restProps
    } = props;

    const s2Options = React.useMemo<SheetComponentOptions>(() => {
      const options: SheetComponentOptions = {
        dataCell: (viewMeta, spreadsheet) =>
          new ChartSheetDataCell(viewMeta, spreadsheet),
        showDefaultHeaderActionIcon: false,
        interaction: {
          hoverFocus: false,
          brushSelection: {
            dataCell: false,
          },
        },
        style: {
          colCell: {
            hideValue: true,
          },
          rowCell: {
            width: 100,
          },
          dataCell: {
            width: 400,
            height: 400,
          },
        },
        tooltip: {
          enable: true,
        },
      };

      return customMerge<SheetComponentOptions>(defaultOptions, options);
    }, [defaultOptions]);

    const themeCfg = React.useMemo<ThemeCfg>(() => {
      const theme: ThemeCfg['theme'] = {
        dataCell: {
          cell: {
            interactionState: {
              hoverFocus: {
                borderOpacity: 0,
              },
              selected: {
                borderOpacity: 0,
              },
            },
          },
        },
      };

      return customMerge<ThemeCfg>(defaultThemeCfg, {
        theme,
      });
    }, [defaultThemeCfg]);

    return <BaseSheet {...restProps} options={s2Options} themeCfg={themeCfg} />;
  },
);

ChartSheet.displayName = 'ChartSheet';
