// packages/s2-react/playground/components/ChartSheet.tsx
/* eslint-disable import/no-extraneous-dependencies */
// import { renderToMountedElement, stdlib } from '@antv/g2';
import { type SpreadSheet } from '@antv/s2';
import React from 'react';
import { ChartDataConfig } from '../../__tests__/data/data-g2-chart';
import {
  SheetComponent,
  type SheetComponentOptions,
  type SheetComponentProps,
} from '../../src/components';
import { usePlaygroundContext } from '../context/playground.context';

const options: SheetComponentOptions = {
  height: 900,
  interaction: {
    copy: { enable: true, withFormat: true },
    brushSelection: {
      rowCell: true,
      colCell: true,
      dataCell: false,
    },
    selectedCellMove: true,
    selectedCellHighlight: true,
    selectedCellsSpotlight: true,
    hoverFocus: true,
    hoverHighlight: false,
    multiSelection: true,
    overscrollBehavior: 'none',
  },
  style: {},
};

export const ChartSheet = React.forwardRef<
  SpreadSheet,
  Partial<SheetComponentProps>
>((props, ref) => {
  const context = usePlaygroundContext();

  return (
    <SheetComponent
      {...props}
      {...context}
      sheetType="chart"
      dataCfg={ChartDataConfig}
      options={options}
      ref={ref}
      adaptive={true}
      header={{
        title: 'S2 & G2',
        description: '单元格内绘制 G2 图表',
        export: { open: true },
      }}
    />
  );
});

// packages/s2-vue/playground/components/ChartSheet.vue
<script setup lang="ts">
import { ref } from 'vue';
import type { S2Options } from '@antv/s2';
import { ChartDataCell } from '@antv/s2/extends';
import { SheetComponent } from '../../src';
import { ChartDataConfig } from '../../__tests__/data/data-g2-chart';

const options = ref<S2Options>({
  height: 900,
  style: {
    rowCell: { width: 100 },
    dataCell: { width: 400, height: 400 },
  },
  tooltip: { enable: true },
  dataCell: (viewMeta, spreadsheet) => new ChartDataCell(viewMeta, spreadsheet),
  showDefaultHeaderActionIcon: false,
  interaction: {
    copy: { enable: true, withFormat: true },
    brushSelection: {
      rowCell: true,
      colCell: true,
      dataCell: false,
    },
    selectedCellMove: true,
    selectedCellHighlight: true,
    selectedCellsSpotlight: true,
    hoverFocus: true,
    hoverHighlight: false,
    multiSelection: true,
    overscrollBehavior: 'none',
  },
});
</script>

<template>
  <div>
    <h3>图表表格 (Chart Sheet)</h3>
    <p>在单元格中渲染 G2 图表</p>
    <SheetComponent
      sheetType="chart"
      :dataCfg="ChartDataConfig"
      :options="options"
      :adaptive="true"
    />
  </div>
</template>
