// packages/s2-vue/src/components/pagination/index.vue
<script lang="ts">
import { computed, defineComponent } from 'vue';
import { S2_PREFIX_CLS } from '@antv/s2';
import { Pagination as AntDPagination } from 'ant-design-vue';
import { i18n } from '@antv/s2';
import {
  DEFAULT_PAGE_NUMBER,
  DEFAULT_PAGE_SIZE,
} from '../../hooks/usePagination';

const PRE_CLASS = `${S2_PREFIX_CLS}-pagination`;

export default defineComponent({
  name: 's2-pagination',
  props: {
    current: {
      type: Number,
      default: DEFAULT_PAGE_NUMBER,
    },
    total: {
      type: Number,
      default: 0,
    },
    pageSize: {
      type: Number,
      default: DEFAULT_PAGE_SIZE,
    },
  },
  emits: ['change', 'showSizeChange'] as unknown as {
    change: (pagination: { current: number; pageSize: number }) => void;
    showSizeChange: (pagination: { current: number; pageSize: number }) => void;
  },
  setup: (props) => {
    // only show the pagination when the pageSize > 5
    const showQuickJumper = computed(() => {
      return props.total / props.pageSize > 5;
    });

    return {
      showQuickJumper,
      PRE_CLASS,
      i18n,
    };
  },
  components: {
    AntDPagination,
  },
});
</script>

<template>
  <div :class="PRE_CLASS">
    <AntDPagination
      :default-current="1"
      :current="current"
      :total="total"
      :pageSize="pageSize"
      :showSizeChanger="true"
      @showSizeChange="
        (current, pageSize) => $emit('showSizeChange', { current, pageSize })
      "
      size="small"
      :showQuickJumper="showQuickJumper"
      @change="(current, pageSize) => $emit('change', { current, pageSize })"
    />
    <span :class="`${PRE_CLASS}-count`">
      {{ i18n('共计') }} {{ total || ' - ' }} {{ i18n('条') }}
    </span>
  </div>
</template>

// packages/s2-react/src/components/pagination/index.tsx
import React from 'react';
import { Pagination as AntdPagination } from 'antd';
import { isEmpty } from 'lodash';
import { i18n, S2_PREFIX_CLS } from '@antv/s2';
import type { S2Options } from '@antv/s2';

export interface S2PaginationProps {
  pagination: S2Options['pagination'];
  onShowSizeChange?: (current: number, pageSize: number) => void;
  onChange?: (current: number, pageSize: number) => void;
}

const PRE_CLASS = `${S2_PREFIX_CLS}-pagination`;

export const S2Pagination: React.FC<S2PaginationProps> = ({
  pagination,
  onShowSizeChange,
  onChange,
}) => {
  // not show the pagination
  if (isEmpty(pagination)) {
    return null;
  }

  const { total, pageSize } = pagination;
  // only show the pagination when the pageSize > 5
  const showQuickJumper = total! / pageSize > 5;

  return (
    <div className={PRE_CLASS}>
      <AntdPagination
        size="small"
        defaultCurrent={1}
        showSizeChanger
        showQuickJumper={showQuickJumper}
        {...pagination}
        onShowSizeChange={onShowSizeChange}
        onChange={onChange}
      />
      <span
        className={`${PRE_CLASS}-count`}
        title={`${i18n('共计')}${total}${i18n('条')}`}
      >
        {i18n('共计')}
        {total || ' - '}
        {i18n('条')}
      </span>
    </div>
  );
};

S2Pagination.displayName = 'S2Pagination';
