// packages/s2-vue/playground/components/CustomTree.vue
<script setup lang="ts">
import { ref } from 'vue';
import type { S2DataConfig, S2Options, HierarchyType } from '@antv/s2';
import { SheetComponent } from '../../src';
import { customTreeData, customTreeFields } from '../config';

const hierarchyType = ref<HierarchyType>('tree');

const dataCfg = ref<S2DataConfig>({
  data: customTreeData,
  fields: customTreeFields,
});

const options = ref<S2Options>({
  debug: true,
  width: 600,
  height: 480,
  hierarchyType: 'tree',
  showDefaultHeaderActionIcon: false,
  interaction: {
    copy: {
      enable: true,
      withHeader: true,
      withFormat: true,
    },
  },
  style: {
    rowCell: {},
  },
});

const toggleHierarchy = (checked: boolean) => {
  hierarchyType.value = checked ? 'tree' : 'grid';
};
</script>

<template>
  <div>
    <a-space style="margin-bottom: 8px">
      <a-switch
        checked-children="树状"
        un-checked-children="平铺"
        :checked="hierarchyType === 'tree'"
        @change="toggleHierarchy"
      />
    </a-space>
    <SheetComponent
      sheetType="pivot"
      :dataCfg="dataCfg"
      :options="{ ...options, hierarchyType }"
      :adaptive="false"
    />
  </div>
</template>

// packages/s2-react/playground/CustomTree.tsx
import type { S2DataConfig } from '@antv/s2';
import React from 'react';
import { SheetComponent, type SheetComponentOptions } from '../src';
import { customTreeFields } from '../__tests__/data/custom-tree-fields';
import { customTreeData } from '../__tests__/data/data-custom-trees';
import { meta } from '../__tests__/data/mock-dataset.json';

export const customTreeDataCfg: S2DataConfig = {
  meta,
  data: customTreeData,
  fields: customTreeFields,
};

export const customTreeOptions: SheetComponentOptions = {
  width: 600,
  height: 480,
  hierarchyType: 'tree',
  cornerText: '指标',
};

export const CustomTree = () => {
  return (
    <SheetComponent dataCfg={customTreeDataCfg} options={customTreeOptions} />
  );
};
