// packages/s2-react-components/src/components/analysis/advanced-sort/advanced-sort.tsx
import { DeleteOutlined, OrderedListOutlined } from '@ant-design/icons';
import { EXTRA_FIELD, TOTAL_VALUE, i18n, type SortParam } from '@antv/s2';
import {
  ADVANCED_SORT_PRE_CLS,
  getSortMethod,
  getSortRuleOptions,
} from '@antv/s2-shared';
import { Button, Cascader, Form, Layout, Modal, Radio, Select } from 'antd';
import cx from 'classnames';
import {
  filter,
  find,
  forEach,
  includes,
  isEqual,
  keys,
  map,
  toUpper,
  uniq,
} from 'lodash';
import React, { useEffect, useState } from 'react';
import { CustomSort } from './custom-sort';
import './index.less';
import type {
  AdvancedSortProps,
  Dimension,
  RuleItem,
  RuleValue,
} from './interface';

const { Sider, Content } = Layout;

export const AdvancedSort: React.FC<AdvancedSortProps> = React.memo(
  ({
    sheetInstance,
    className,
    icon,
    text,
    ruleText,
    dimensions,
    ruleOptions,
    sortParams,
    onSortOpen,
    onSortConfirm,
  }) => {
    const [isSortVisible, setIsModalVisible] = useState(false);
    const [isCustomVisible, setIsCustomVisible] = useState(false);
    const [ruleList, setRuleList] = useState<RuleItem[]>([]);
    const [rules, setRules] = useState<RuleItem[]>([]);
    const [manualDimensionList, setManualDimensionList] = useState<Dimension[]>(
      [],
    );
    const [dimensionList, setDimensionList] = useState<Dimension[]>([]);
    const [sortBy, setSortBy] = useState<string[]>([]);
    const [currentDimension, setCurrentDimension] = useState<Dimension>();
    const [form] = Form.useForm();

    const SORT_RULE_OPTIONS = React.useMemo(getSortRuleOptions, []);
    const SORT_METHOD = React.useMemo(getSortMethod, []);

    const handleModal = () => {
      setIsModalVisible(!isSortVisible);
    };

    const sortClick = () => {
      if (onSortOpen) {
        onSortOpen();
      }

      handleModal();
    };

    const handleCustom = () => {
      setIsCustomVisible(!isCustomVisible);
    };

    const handleDimension = (dimension: Dimension) => {
      if (!find(ruleList, (item) => item.field === dimension.field)) {
        setCurrentDimension(dimension);
        setRuleList([...ruleList, dimension] as RuleItem[]);
      }

      setDimensionList(
        filter(dimensionList, (item) => item.field !== dimension.field),
      );
    };

    const handleCustomSort = (dimension: Dimension, splitOrders?: string[]) => {
      handleCustom();
      setCurrentDimension(dimension);
      if (splitOrders) {
        setSortBy(uniq(splitOrders));
      } else {
        setSortBy(
          uniq(
            find(manualDimensionList, (item) => item.field === dimension.field)
              ?.list || [],
          ),
        );
      }
    };

    const customSort = () => {
      handleCustom();
      const currentFieldValue = form.getFieldsValue([currentDimension?.field!]);

      currentFieldValue.sortBy = sortBy;
      form.setFieldsValue({ [currentDimension?.field!]: currentFieldValue });
      const newRuleList = map(ruleList, (item) => {
        if (item.field === currentDimension?.field) {
          return {
            ...item,
            rule: 'sortBy',
            sortBy,
            sortMethod: '',
            sortByMeasure: '',
          };
        }

        return item;
      }) as unknown as RuleItem[];

      setRuleList(newRuleList);
    };

    const customCancel = () => {
      handleCustom();
    };

    const deleteRule = (dimension: Dimension) => {
      setRuleList(filter(ruleList, (item) => item.field !== dimension.field));
      setDimensionList([...dimensionList, dimension]);
    };

    const onFinish = () => {
      const ruleValue = form.getFieldsValue();
      const { values = [] } = sheetInstance.dataCfg.fields;
      const ruleValues: RuleValue[] = [];
      const currentSortParams: SortParam[] = [];

      forEach(keys(ruleValue), (item) => {
        const {
          sortMethod,
          rule = [],
          sortBy: currentSortBy,
        } = ruleValue[item];
        const current: SortParam = { sortFieldId: item };

        if (rule[0] === 'sortByMeasure' || rule[1]) {
          // 如果不是数值 key ，则按照汇总值排序
          if (!includes(values, rule[1])) {
            current.sortByMeasure = TOTAL_VALUE;
          } else {
            current.sortByMeasure = rule[1];
          }

          current.sortMethod = sortMethod;
          current.query = {
            [EXTRA_FIELD]: rule[1],
          };
        } else if (rule[0] === 'sortBy') {
          current.sortBy = currentSortBy;
        } else {
          current.sortMethod = sortMethod;
        }

        ruleValues.push({ field: item, ...ruleValue[item] });
        currentSortParams.push(current);
      });
      if (onSortConfirm) {
        onSortConfirm(ruleValues, currentSortParams);
      }

      handleModal();
    };

    const getDimensionList = (list: Dimension[]) =>
      filter(
        list,
        (item: Dimension) =>
          !find(
            sortParams,
            (sortParam) => sortParam.sortFieldId === item.field,
          ),
      );

    const getManualDimensionList = (): Dimension[] => {
      if (dimensions) {
        return dimensions;
      }

      const { fields = {} } = sheetInstance.dataCfg || {};
      const { rows = [], columns = [] } = fields;

      return map([...rows, ...columns], (item) => {
        const name = typeof item === 'string' ? item : item.field;

        return {
          field: item,
          name: sheetInstance.dataSet.getFieldName(name),
          list: sheetInstance.dataSet.getDimensionValues(name),
        };
      }) as unknown as Dimension[];
    };

    const getRuleOptions = () => {
      if (ruleOptions) {
        return ruleOptions;
      }

      return map(SORT_RULE_OPTIONS, (item) => {
        if (item.value === 'sortByMeasure') {
          const { values = [] } = sheetInstance.dataCfg.fields || {};

          // @ts-ignore
          item.children = map(values, (field) => {
            return {
              label: sheetInstance.dataSet.getFieldName(field),
              value: field,
            };
          });
        }

        return item;
      });
    };

    const getRuleList = (): RuleItem[] =>
      map(sortParams, (item) => {
        const {
          sortFieldId,
          sortMethod,
          sortBy: currentSortBy,
          sortByMeasure,
        } = item;
        let rule: string[];

        if (currentSortBy) {
          rule = ['sortBy'];
        } else if (sortByMeasure) {
          rule = ['sortByMeasure', sortByMeasure];
        } else {
          rule = ['sortMethod'];
        }

        return {
          field: sortFieldId,
          name: sheetInstance.dataSet.getFieldName(sortFieldId),
          rule,
          sortMethod,
          sortBy: currentSortBy,
          sortByMeasure,
        };
      });

    const renderSide = () => (
      <Sider width={120} className={`${ADVANCED_SORT_PRE_CLS}-sider-layout`}>
        <div className={`${ADVANCED_SORT_PRE_CLS}-title`}>
          {i18n('可选字段')}
        </div>
        <div>
          {map(dimensionList, (item) => (
            <div
              className={`${ADVANCED_SORT_PRE_CLS}-dimension-item`}
              key={item.field}
              title={item.name}
              onClick={() => {
                handleDimension(item);
              }}
            >
              {item.name}
            </div>
          ))}
        </div>
      </Sider>
    );

    const renderContent = () => (
      <Content className={`${ADVANCED_SORT_PRE_CLS}-content-layout`}>
        <div className={`${ADVANCED_SORT_PRE_CLS}-title`}>
          {ruleText || i18n('按以下规则进行排序（优先级由低到高）')}
        </div>
        <Form
          form={form}
          name="form"
          className={`${ADVANCED_SORT_PRE_CLS}-custom-form`}
        >
          {map(ruleList, (item) => {
            const {
              field,
              name,
              rule,
              sortMethod,
              sortBy: currentSortBy,
            } = item || {};

            return (
              <Form.Item key={field}>
                <Form.Item name={[field, 'name']} initialValue={name} noStyle>
                  <Select
                    className={`${ADVANCED_SORT_PRE_CLS}-select`}
                    size="small"
                  />
                </Form.Item>
                <span className={`${ADVANCED_SORT_PRE_CLS}-field-prefix`}>
                  {i18n('按')}
                </span>
                <Form.Item
                  name={[field, 'rule']}
                  initialValue={rule || ['sortMethod']}
                  noStyle
                >
                  <Cascader
                    options={rules}
                    expandTrigger="hover"
                    size="small"
                    allowClear={false}
                  />
                </Form.Item>
                <Form.Item shouldUpdate noStyle>
                  {({ getFieldValue }) =>
                    !isEqual(getFieldValue([field, 'rule']), ['sortBy']) ? (
                      <Form.Item
                        shouldUpdate
                        noStyle
                        name={[field, 'sortMethod']}
                        initialValue={toUpper(sortMethod) || 'ASC'}
                      >
                        <Radio.Group
                          className={`${ADVANCED_SORT_PRE_CLS}-rule-end`}
                        >
                          {map(SORT_METHOD, (i) => (
                            <Radio value={i.value} key={i.value}>
                              {i.name}
                            </Radio>
                          ))}
                        </Radio.Group>
                      </Form.Item>
                    ) : (
                      <>
                        <a
                          className={`${ADVANCED_SORT_PRE_CLS}-rule-end`}
                          onClick={() => {
                            handleCustomSort(
                              item as unknown as Dimension,
                              currentSortBy,
                            );
                          }}
                        >
                          {i18n('设置顺序')}
                        </a>
                        <Form.Item
                          noStyle
                          name={[field, 'sortBy']}
                          initialValue={currentSortBy}
                        />
                      </>
                    )
                  }
                </Form.Item>
                <DeleteOutlined
                  className={`${ADVANCED_SORT_PRE_CLS}-rule-end-delete`}
                  onClick={() => {
                    deleteRule(item as unknown as Dimension);
                  }}
                />
              </Form.Item>
            );
          })}
        </Form>
      </Content>
    );

    useEffect(() => {
      if (isSortVisible) {
        const initRuleList = getRuleList();
        const manualDimensions = getManualDimensionList();
        const initDimensionList = getDimensionList(
          manualDimensions,
        ) as Dimension[];
        const initRuleOptions = getRuleOptions() as unknown as RuleItem[];

        setRuleList(initRuleList);
        setManualDimensionList(manualDimensions);
        setDimensionList(initDimensionList);
        setRules(initRuleOptions);
      }
    }, [isSortVisible]);

    return (
      <div className={cx(ADVANCED_SORT_PRE_CLS, className)}>
        <Button
          onClick={sortClick}
          icon={icon || <OrderedListOutlined />}
          size="small"
          className={`${ADVANCED_SORT_PRE_CLS}-btn`}
        >
          {text || i18n('高级排序')}
        </Button>
        <Modal
          title={text || i18n('高级排序')}
          open={isSortVisible}
          onOk={onFinish}
          onCancel={handleModal}
          okText={i18n('确定')}
          cancelText={i18n('取消')}
          destroyOnClose
          className={`${ADVANCED_SORT_PRE_CLS}-modal`}
        >
          <Layout>
            {renderSide()}
            {renderContent()}
          </Layout>
        </Modal>
        <Modal
          title={i18n('手动排序')}
          open={isCustomVisible}
          onOk={customSort}
          onCancel={customCancel}
          okText={i18n('确定')}
          cancelText={i18n('取消')}
          destroyOnClose
          className={`${ADVANCED_SORT_PRE_CLS}-custom-modal`}
        >
          <CustomSort splitOrders={sortBy} setSplitOrders={setSortBy} />
        </Modal>
      </div>
    );
  },
);

AdvancedSort.displayName = 'AdvancedSort';

// packages/s2-vue/src/components-extra/advanced-sort/AdvancedSort.vue
<script setup lang="ts">
import { ref, watch } from 'vue';
import {
  Button,
  Form,
  Layout,
  Modal,
  Select,
  Cascader,
  Radio,
  type FormInstance,
} from 'ant-design-vue';
import { OrderedListOutlined, DeleteOutlined } from '@ant-design/icons-vue';
import {
  ADVANCED_SORT_PRE_CLS,
  EXTRA_FIELD,
  TOTAL_VALUE,
  getSortMethod,
  getSortRuleOptions,
  i18n,
  type SortParam,
} from '@antv/s2';
import {
  filter,
  find,
  forEach,
  includes,
  isEqual,
  keys,
  map,
  toUpper,
  uniq,
} from 'lodash';
import type {
  AdvancedSortProps,
  Dimension,
  RuleItem,
  RuleValue,
} from './interface';
import CustomSort from './CustomSort.vue';

const props = defineProps<AdvancedSortProps>();

const emit = defineEmits<{
  (e: 'sort-confirm', ruleValues: RuleValue[], sortParams: SortParam[]): void;
  (e: 'sort-open'): void;
}>();

const { Sider, Content } = Layout;

const isSortVisible = ref(false);
const isCustomVisible = ref(false);
const ruleList = ref<RuleItem[]>([]);
const rules = ref<any[]>([]);
const manualDimensionList = ref<Dimension[]>([]);
const dimensionList = ref<Dimension[]>([]);
const sortBy = ref<string[]>([]);
const currentDimension = ref<Dimension>();
const formRef = ref<FormInstance>();
const formData = ref<Record<string, any>>({});

// Constants
const SORT_RULE_OPTIONS = getSortRuleOptions();
const SORT_METHOD = getSortMethod();

const handleModal = () => {
  isSortVisible.value = !isSortVisible.value;
};

const sortClick = () => {
  emit('sort-open');
  handleModal();
};

const handleCustom = () => {
  isCustomVisible.value = !isCustomVisible.value;
};

const handleDimension = (dimension: Dimension) => {
  if (!find(ruleList.value, (item) => item.field === dimension.field)) {
    currentDimension.value = dimension;
    formData.value[dimension.field] = {
      name: dimension.name,
      rule: ['sortMethod'],
      sortMethod: 'ASC',
      sortBy: [],
    };
    ruleList.value = [...ruleList.value, dimension as unknown as RuleItem];
  }

  dimensionList.value = filter(
    dimensionList.value,
    (item) => item.field !== dimension.field,
  );
};

const handleCustomSort = (dimension: Dimension, splitOrders?: string[]) => {
  handleCustom();
  currentDimension.value = dimension;
  if (splitOrders && splitOrders.length > 0) {
    sortBy.value = uniq(splitOrders);
  } else {
    const list =
      find(manualDimensionList.value, (item) => item.field === dimension.field)
        ?.list || [];

    sortBy.value = uniq(list);
  }
};

const customSort = () => {
  handleCustom();
  // Update formData directly since we are using v-model / form binding
  // In React strict controlled form: form.setFieldsValue.
  // In Vue we might need to manually update if we use v-model on form items
  // But here we might rely on re-initializing form state or reactivity.

  if (!currentDimension.value) {
    return;
  }

  const field = currentDimension.value.field;

  // Update local state that reflects back to form
  if (!formData.value[field]) {
    formData.value[field] = {};
  }

  formData.value[field].sortBy = sortBy.value;

  // Update ruleList 's view
  ruleList.value = map(ruleList.value, (item) => {
    if (item.field === field) {
      return {
        ...item,
        // Force rule to sortBy
        rule: ['sortBy'],
        sortBy: sortBy.value,
        sortMethod: undefined,
        sortByMeasure: undefined,
      };
    }

    return item;
  }) as RuleItem[];

  // Also update Form data explicitly if needed (Antdv Form)
  if (formRef.value) {
    formRef.value.validateFields();
  }
};

const customCancel = () => {
  handleCustom();
};

const deleteRule = (dimension: Dimension) => {
  ruleList.value = filter(
    ruleList.value,
    (item) => item.field !== dimension.field,
  );
  dimensionList.value = [...dimensionList.value, dimension];

  // Clean up form data
  delete formData.value[dimension.field];
};

const onFinish = () => {
  const ruleValues: RuleValue[] = [];
  const currentSortParams: SortParam[] = [];

  // Use formData.value instead of form.getFieldsValue() if we bind v-model
  // Or use formRef.value.getFieldsValue(). simpler to trust reactive state here,
  // but for Antdv Form, getting all fields value is safer.

  // Let's assume formData.value is sync with UI via v-model
  const formValues = formData.value;
  const { values = [] } = props.sheetInstance.dataCfg.fields;

  forEach(keys(formValues), (field) => {
    // Check if valid rule in list
    if (!find(ruleList.value, (r) => r.field === field)) {
      return;
    }

    const { sortMethod, rule = [], sortBy: currentSortBy } = formValues[field];

    // Default fallback
    const safeRule = rule || ['sortMethod'];

    const current: SortParam = { sortFieldId: field };

    if (safeRule[0] === 'sortByMeasure' || safeRule[1]) {
      if (!includes(values, safeRule[1])) {
        current.sortByMeasure = TOTAL_VALUE;
      } else {
        current.sortByMeasure = safeRule[1];
      }

      current.sortMethod = sortMethod;
      current.query = {
        [EXTRA_FIELD]: safeRule[1],
      };
    } else if (safeRule[0] === 'sortBy') {
      current.sortBy = currentSortBy;
    } else {
      current.sortMethod = sortMethod;
    }

    ruleValues.push({
      field,
      name: '',
      sortMethod: formValues[field].sortMethod,
      sortBy: formValues[field].sortBy,
      sortByMeasure: formValues[field].sortByMeasure,
      rule: formValues[field].rule,
    });
    currentSortParams.push(current);
  });

  emit('sort-confirm', ruleValues, currentSortParams);
  handleModal();
};

const getDimensionList = (list: Dimension[]) =>
  filter(
    list,
    (item: Dimension) =>
      !find(
        props.sortParams,
        (sortParam) => sortParam.sortFieldId === item.field,
      ),
  );

const getManualDimensionList = (): Dimension[] => {
  if (props.dimensions) {
    return props.dimensions;
  }

  const { fields = {} } = props.sheetInstance.dataCfg || {};
  const { rows = [], columns = [] } = fields;

  return map([...rows, ...columns], (item: any) => {
    const name = typeof item === 'string' ? item : item.field;

    return {
      field: item,
      name: props.sheetInstance.dataSet.getFieldName(name),
      list: props.sheetInstance.dataSet.getDimensionValues(name),
    };
  }) as unknown as Dimension[];
};

const getRuleOptions = () => {
  if (props.ruleOptions) {
    return props.ruleOptions;
  }

  return map(SORT_RULE_OPTIONS, (item) => {
    if (item.value === 'sortByMeasure') {
      const { values = [] } = props.sheetInstance.dataCfg.fields || {};

      item.children = map(values, (field) => {
        return {
          label: props.sheetInstance.dataSet.getFieldName(field),
          value: field,
        };
      });
    }

    return item;
  });
};

const getRuleList = (): RuleItem[] =>
  map(props.sortParams, (item) => {
    const {
      sortFieldId,
      sortMethod,
      sortBy: currentSortBy,
      sortByMeasure,
    } = item;
    let rule: string[];

    if (currentSortBy) {
      rule = ['sortBy'];
    } else if (sortByMeasure) {
      rule = ['sortByMeasure', sortByMeasure];
    } else {
      rule = ['sortMethod'];
    }

    return {
      field: sortFieldId,
      name: props.sheetInstance.dataSet.getFieldName(sortFieldId),
      rule,
      sortMethod,
      sortBy: currentSortBy,
      sortByMeasure,
    };
  }) as RuleItem[];

watch(isSortVisible, (val) => {
  if (val) {
    const initRuleList = getRuleList();
    const manualDimensions = getManualDimensionList();
    const initDimensionList = getDimensionList(manualDimensions);
    const initRuleOptions = getRuleOptions();

    ruleList.value = initRuleList;
    manualDimensionList.value = manualDimensions;
    dimensionList.value = initDimensionList;
    rules.value = initRuleOptions;

    // Initialize form data
    const newFormData: Record<string, any> = {};

    initRuleList.forEach((item) => {
      newFormData[item.field] = {
        name: item.name,
        rule: item.rule,
        sortMethod: item.sortMethod ? toUpper(item.sortMethod) : 'ASC',
        sortBy: item.sortBy,
      };
    });
    formData.value = newFormData;
  }
});

const onSplitOrdersChange = (orders: string[]) => {
  sortBy.value = orders;
};
</script>

<template>
  <div :class="[ADVANCED_SORT_PRE_CLS, className]">
    <Button
      size="small"
      :class="`${ADVANCED_SORT_PRE_CLS}-btn`"
      @click="sortClick"
    >
      <template #icon>
        <component :is="icon || OrderedListOutlined" />
      </template>
      {{ text || i18n('高级排序') }}
    </Button>

    <Modal
      :title="text || i18n('高级排序')"
      :open="isSortVisible"
      :okText="i18n('确定')"
      :cancelText="i18n('取消')"
      :destroyOnClose="true"
      :class="`${ADVANCED_SORT_PRE_CLS}-modal`"
      @ok="onFinish"
      @cancel="handleModal"
    >
      <Layout>
        <Sider width="120" :class="`${ADVANCED_SORT_PRE_CLS}-sider-layout`">
          <div :class="`${ADVANCED_SORT_PRE_CLS}-title`">
            {{ i18n('可选字段') }}
          </div>
          <div>
            <div
              v-for="item in dimensionList"
              :key="item.field"
              :class="`${ADVANCED_SORT_PRE_CLS}-dimension-item`"
              :title="item.name"
              @click="handleDimension(item)"
            >
              {{ item.name }}
            </div>
          </div>
        </Sider>
        <Content :class="`${ADVANCED_SORT_PRE_CLS}-content-layout`">
          <div :class="`${ADVANCED_SORT_PRE_CLS}-title`">
            {{ ruleText || i18n('按以下规则进行排序（优先级由低到高）') }}
          </div>
          <Form
            ref="formRef"
            :model="formData"
            name="form"
            :class="`${ADVANCED_SORT_PRE_CLS}-custom-form`"
          >
            <div v-for="item in ruleList" :key="item.field">
              <!-- Field Name (ReadOnly) -->
              <Form.Item style="margin-bottom: 4px">
                <Select
                  :value="item.name"
                  disabled
                  :class="`${ADVANCED_SORT_PRE_CLS}-select`"
                  size="small"
                  style="width: 120px"
                />
                <span :class="`${ADVANCED_SORT_PRE_CLS}-field-prefix`">
                  {{ i18n('按') }}
                </span>

                <!-- Rule Cascader -->
                <Form.Item :name="[item.field, 'rule']" noStyle>
                  <Cascader
                    v-model:value="formData[item.field].rule"
                    :options="rules"
                    expandTrigger="hover"
                    size="small"
                    :allowClear="false"
                    style="width: 120px; margin-left: 8px"
                  />
                </Form.Item>

                <!-- Conditional Render based on rule -->
                <template
                  v-if="!isEqual(formData[item.field].rule, ['sortBy'])"
                >
                  <Form.Item :name="[item.field, 'sortMethod']" noStyle>
                    <Radio.Group
                      v-model:value="formData[item.field].sortMethod"
                      :class="`${ADVANCED_SORT_PRE_CLS}-rule-end`"
                    >
                      <Radio
                        v-for="method in SORT_METHOD"
                        :key="method.value"
                        :value="method.value"
                      >
                        {{ method.name }}
                      </Radio>
                    </Radio.Group>
                  </Form.Item>
                </template>
                <template v-else>
                  <a
                    :class="`${ADVANCED_SORT_PRE_CLS}-rule-end`"
                    @click="
                      handleCustomSort(
                        item as unknown as Dimension,
                        formData[item.field].sortBy,
                      )
                    "
                  >
                    {{ i18n('设置顺序') }}
                  </a>
                  <!-- Hidden sortBy field storage -->
                  <!-- formData[item.field].sortBy is stored in state -->
                </template>

                <DeleteOutlined
                  :class="`${ADVANCED_SORT_PRE_CLS}-rule-end-delete`"
                  @click="deleteRule(item as unknown as Dimension)"
                />
              </Form.Item>
            </div>
          </Form>
        </Content>
      </Layout>
    </Modal>

    <Modal
      :title="i18n('手动排序')"
      :open="isCustomVisible"
      :okText="i18n('确定')"
      :cancelText="i18n('取消')"
      :destroyOnClose="true"
      :class="`${ADVANCED_SORT_PRE_CLS}-custom-modal`"
      @ok="customSort"
      @cancel="customCancel"
    >
      <CustomSort
        :splitOrders="sortBy"
        @split-orders-change="onSplitOrdersChange"
      />
    </Modal>
  </div>
</template>

<style lang="less">
@import './index.less';
</style>
