// packages/s2-react/src/components/drill-down/index.tsx
import React, { type ReactNode, useEffect, useState } from 'react';
import { Button, ConfigProvider, Empty, Input, Menu } from 'antd';
import cx from 'classnames';
import { isEmpty } from 'lodash';
import type { BaseDataSet, BaseDrillDownComponentProps } from '@antv/s2-shared';
import { i18n } from '@antv/s2';
import { DRILL_DOWN_PRE_CLASS } from '@antv/s2-shared';
import {
  CalendarIcon,
  LocationIcon,
  SearchIcon,
  TextIcon,
} from '../icons/index';

import '@antv/s2-shared/src/styles/drill-down.less';

export interface DrillDownDataSet extends BaseDataSet {
  icon?: React.ReactNode;
}

export interface DrillDownProps
  extends BaseDrillDownComponentProps<DrillDownDataSet> {
  extra?: ReactNode;
}

export const DrillDown: React.FC<DrillDownProps> = ({
  className,
  titleText = i18n('选择下钻维度'),
  clearButtonText = i18n('恢复默认'),
  searchText = i18n('搜索字段'),
  extra,
  drillFields,
  dataSet = [],
  disabledFields,
  getDrillFields,
  setDrillFields,
  ...restProps
}) => {
  const DRILL_DOWN_ICON_MAP = {
    text: <TextIcon />,
    location: <LocationIcon />,
    date: <CalendarIcon />,
  };

  const getOptions = () =>
    dataSet.map((val: DrillDownDataSet) => {
      val.disabled = !!(disabledFields && disabledFields.includes(val.value));

      return val;
    });

  const [options, setOptions] = useState<DrillDownDataSet[]>(getOptions());

  const handleSearch = (e: any) => {
    const { value } = e.target;

    if (!value) {
      setOptions([...dataSet]);
    } else {
      const reg = new RegExp(value, 'gi');
      const result = dataSet.filter((item) => reg.test(item.name));

      setOptions([...result]);
    }
  };

  const handleSelect = (value: any) => {
    const key = value?.selectedKeys;

    if (getDrillFields) {
      getDrillFields([...key]);
    }

    if (setDrillFields) {
      setDrillFields([...key]);
    }
  };

  const handleClear = (e: React.MouseEvent<HTMLElement>) => {
    e.stopPropagation();
    if (getDrillFields) {
      getDrillFields([]);
    }

    if (setDrillFields) {
      setDrillFields([]);
    }
  };

  useEffect(() => {
    setOptions(getOptions());
  }, [disabledFields]);

  return (
    <ConfigProvider>
      <div className={cx(DRILL_DOWN_PRE_CLASS, className)} {...restProps}>
        <header className={`${DRILL_DOWN_PRE_CLASS}-header`}>
          <div>{titleText}</div>
          <Button
            type="link"
            disabled={isEmpty(drillFields)}
            onClick={handleClear}
          >
            {clearButtonText}
          </Button>
        </header>
        <Input
          className={`${DRILL_DOWN_PRE_CLASS}-search`}
          placeholder={searchText}
          onChange={handleSearch}
          onPressEnter={handleSearch}
          prefix={<SearchIcon />}
          allowClear
        />
        <div className={`${DRILL_DOWN_PRE_CLASS}-extra`}>{extra}</div>
        {isEmpty(options) && (
          <Empty
            imageStyle={{ height: '64px' }}
            className={`${DRILL_DOWN_PRE_CLASS}-empty`}
          />
        )}
        <Menu
          className={`${DRILL_DOWN_PRE_CLASS}-menu`}
          selectedKeys={drillFields}
          onSelect={handleSelect}
        >
          {options.map((option) => (
            <Menu.Item
              key={option.value}
              disabled={option.disabled}
              className={`${DRILL_DOWN_PRE_CLASS}-menu-item`}
              icon={
                option.icon ? option.icon : DRILL_DOWN_ICON_MAP[option.type!]
              }
            >
              {option.name}
            </Menu.Item>
          ))}
        </Menu>
      </div>
    </ConfigProvider>
  );
};

// packages/s2-vue/src/components/drill-down/index.vue
<script lang="ts">
import { defineComponent, ref } from 'vue';
import type { Ref } from 'vue';
import type { BaseDataSet, BaseDrillDownComponentProps } from '@antv/s2-shared';
import { Button, Input, Empty, Menu, MenuItem } from 'ant-design-vue';
import type { SelectInfo } from 'ant-design-vue/lib/menu/src/interface';
import { isEmpty } from 'lodash';
import LocationIcon from '@antv/s2-shared/src/icons/location-icon.svg?component';
import TextIcon from '@antv/s2-shared/src/icons/text-icon.svg?component';
import CalendarIcon from '@antv/s2-shared/src/icons/calendar-icon.svg?component';
import type { Key } from 'ant-design-vue/lib/_util/type';
import type { ChangeEvent } from 'ant-design-vue/lib/_util/EventInterface';
import { DRILL_DOWN_PRE_CLASS } from '@antv/s2-shared';
import {
  initDrillDownEmits,
  initDrillDownProps,
} from '../../utils/initPropAndEmits';

export default defineComponent({
  name: 'DrillDown',
  props: initDrillDownProps(),
  emits: initDrillDownEmits(),
  methods: {},
  components: {
    Button,
    Input,
    Empty,
    Menu,
    MenuItem,
    LocationIcon,
    TextIcon,
    CalendarIcon,
  },
  setup(props) {
    const {
      dataSet,
      disabledFields,
      getDrillFields,
      setDrillFields,
      className,
    } = props as BaseDrillDownComponentProps;
    const getOptions = () => {
      return dataSet.map((val: BaseDataSet) => {
        val.disabled = !!(disabledFields && disabledFields.includes(val.value));
        return val;
      });
    };

    const options: Ref<BaseDataSet[]> = ref(getOptions());
    const selected = ref<Key[]>([]);

    const handleSearch = (e: ChangeEvent) => {
      const { value } = e.target;

      if (!value) {
        options.value = [...dataSet];
      } else {
        const reg = new RegExp(value, 'gi');
        const result = dataSet.filter((item) => reg.test(item.name));
        options.value = [...result];
      }
    };

    const handleSelect = (value: SelectInfo) => {
      const key = value?.selectedKeys;
      selected.value = key;
      if (getDrillFields) {
        getDrillFields(key as string[]);
      }
      if (setDrillFields) {
        setDrillFields(key as string[]);
      }
    };

    const handleClear = (e: { stopPropagation: () => void }) => {
      e.stopPropagation();
      selected.value = [];
      if (getDrillFields) {
        getDrillFields([]);
      }
      if (setDrillFields) {
        setDrillFields([]);
      }
    };

    return {
      options,
      handleSearch,
      handleSelect,
      handleClear,
      className,
      selected,
      isEmpty,
      DRILL_DOWN_PRE_CLASS,
    };
  },
});
</script>

<template>
  <div :class="[DRILL_DOWN_PRE_CLASS, className]">
    <header :class="`${DRILL_DOWN_PRE_CLASS}-header`">
      <div>{{ titleText }}</div>
      <Button type="link" @click="handleClear">
        {{ clearButtonText }}
      </Button>
    </header>
    <Input
      :class="`${DRILL_DOWN_PRE_CLASS}-search`"
      :placeholder="searchText"
      @change="handleSearch"
      @pressEnter="handleSearch"
      :allowClear="true"
    />
    <Empty
      v-if="isEmpty(options)"
      :imageStyle="{ height: '64px' }"
      :class="`${DRILL_DOWN_PRE_CLASS}-empty`"
    />
    <Menu
      class="`${DRILL_DOWN_PRE_CLASS}-menu`"
      v-model:selectedKeys="selected"
      @select="handleSelect"
    >
      <MenuItem
        v-for="option in options"
        :key="option.value"
        :disabled="option.disabled"
        :class="`${DRILL_DOWN_PRE_CLASS}-menu-item`"
      >
        <template #icon>
          <text-icon v-if="option.type === 'text'" />
          <calendar-icon v-if="option.type === 'date'" />
          <location-icon v-if="option.type === 'location'" />
        </template>
        {{ option?.name }}
      </MenuItem>
    </Menu>
  </div>
</template>

<style lang="less" scoped>
@import '@antv/s2-shared/src/styles/drill-down.less';
</style>
