// packages/s2-react-components/src/components/frozen-panel/frozen-panel.tsx
import { S2_PREFIX_CLS, i18n } from '@antv/s2';
import { Checkbox } from 'antd';
import type { CheckboxChangeEvent } from 'antd/es/checkbox';
import { isEmpty } from 'lodash';
import React from 'react';
import { ResetGroup } from '../common';
import { FrozenInputNumber } from './frozen-input-number';
import './index.less';
import type { FrozenPanelOptions, FrozenPanelProps } from './interface';

const PRE_CLASS = `${S2_PREFIX_CLS}-frozen-panel`;

export const FrozenPanel: React.FC<FrozenPanelProps> = React.memo((props) => {
  const {
    title = i18n('冻结行列头'),
    defaultOptions: defaultTextAlignPanelOptions,
    defaultCollapsed = false,
    inputNumberProps,
    showFrozenRowHeader = true,
    showFrozenRow = true,
    showFrozenCol = true,
    children,
    onChange,
    onReset,
  } = props;
  const [options, setOptions] = React.useState<FrozenPanelOptions>({
    frozenRow: [],
    frozenCol: [],
    frozenRowHeader: true,
    ...defaultTextAlignPanelOptions,
  });
  const defaultOptions = React.useRef<FrozenPanelOptions>(options);

  const onResetClick = () => {
    setOptions(defaultOptions.current);
    onReset?.(defaultOptions.current, options);
  };

  const onRowHeaderChange = (event: CheckboxChangeEvent) => {
    const newOptions: FrozenPanelOptions = {
      ...options,
      frozenRowHeader: event.target.checked,
    };

    setOptions(newOptions);
    onChange?.(newOptions);
  };

  const BASE_FROZEN_CONFIG: Array<{
    field: keyof Omit<FrozenPanelOptions, 'frozenRowHeader'>;
    suffix: string;
    visible: boolean;
  }> = [
    {
      suffix: i18n('行'),
      field: 'frozenRow' as const,
      visible: showFrozenRow,
    },
    {
      suffix: i18n('列'),
      field: 'frozenCol' as const,
      visible: showFrozenCol,
    },
  ].filter(({ visible }) => visible);

  return (
    <ResetGroup
      title={title}
      onResetClick={onResetClick}
      defaultCollapsed={defaultCollapsed}
      className={PRE_CLASS}
    >
      {showFrozenRowHeader && (
        <div className={`${PRE_CLASS}-container`}>
          <Checkbox
            checked={options.frozenRowHeader}
            onChange={onRowHeaderChange}
          >
            {i18n('冻结行头')}
          </Checkbox>
        </div>
      )}
      {BASE_FROZEN_CONFIG.map((config) => {
        const leadingCount = options[config.field]?.[0];
        const trailingCount = options[config.field]?.[1];
        const enable = !isEmpty(options[config.field]);

        const onGroupChange = (value: [number?, number?]) => {
          const newOptions: FrozenPanelOptions = {
            ...options,
            [config.field]: value,
          };

          setOptions(newOptions);
          onChange?.(newOptions);
        };

        return (
          <div className={`${PRE_CLASS}-container`} key={config.field}>
            <Checkbox
              checked={enable}
              onChange={(event) => {
                onGroupChange(event.target.checked ? [1, 1] : []);
              }}
            >
              {i18n('冻结')}
              {config.suffix}
            </Checkbox>
            <span className={`${PRE_CLASS}-container-group`}>
              {i18n('冻结前')}
              <FrozenInputNumber
                disabled={!enable}
                value={leadingCount!}
                onChange={(val) => {
                  onGroupChange([val, trailingCount]);
                }}
                {...inputNumberProps}
              />
              {config.suffix}
            </span>
            <span className={`${PRE_CLASS}-container-group`}>
              {i18n('冻结后')}
              <FrozenInputNumber
                disabled={!enable}
                value={trailingCount!}
                onChange={(val) => {
                  onGroupChange([leadingCount, val]);
                }}
                {...inputNumberProps}
              />
              {config.suffix}
            </span>
          </div>
        );
      })}
      {children}
    </ResetGroup>
  );
});

FrozenPanel.displayName = 'FrozenPanel';

// packages/s2-vue/src/components-extra/frozen-panel/FrozenPanel.vue
<script setup lang="ts">
import { S2_PREFIX_CLS, i18n } from '@antv/s2';
import { Checkbox, type CheckboxChangeEvent } from 'ant-design-vue';
import { isEmpty } from 'lodash';
import { ref, computed } from 'vue';
import { ResetGroup } from '../common';
import FrozenInputNumber from './FrozenInputNumber.vue';
import type { FrozenPanelOptions } from './interface';

const PRE_CLASS = `${S2_PREFIX_CLS}-frozen-panel`;

const props = withDefaults(
  defineProps<{
    title?: string;
    defaultOptions?: Partial<FrozenPanelOptions>;
    defaultCollapsed?: boolean;
    inputNumberProps?: {
      min?: number;
      max?: number;
      step?: number;
      size?: 'large' | 'middle' | 'small';
    };
    showFrozenRowHeader?: boolean;
    showFrozenRow?: boolean;
    showFrozenCol?: boolean;
  }>(),
  {
    title: () => i18n('冻结行列头'),
    defaultCollapsed: false,
    showFrozenRowHeader: true,
    showFrozenRow: true,
    showFrozenCol: true,
  },
);

const emit = defineEmits<{
  change: [options: FrozenPanelOptions];
  reset: [options: FrozenPanelOptions, prevOptions: FrozenPanelOptions];
}>();

const options = ref<FrozenPanelOptions>({
  frozenRow: [],
  frozenCol: [],
  frozenRowHeader: true,
  ...props.defaultOptions,
});

const defaultOptionsRef = ref<FrozenPanelOptions>({ ...options.value });

const onResetClick = () => {
  const prevOptions = { ...options.value };

  options.value = { ...defaultOptionsRef.value };
  emit('reset', defaultOptionsRef.value, prevOptions);
};

const onRowHeaderChange = (event: CheckboxChangeEvent) => {
  options.value = {
    ...options.value,
    frozenRowHeader: event.target.checked,
  };
  emit('change', options.value);
};

const BASE_FROZEN_CONFIG = computed(() => {
  return [
    {
      suffix: i18n('行'),
      field: 'frozenRow' as const,
      visible: props.showFrozenRow,
    },
    {
      suffix: i18n('列'),
      field: 'frozenCol' as const,
      visible: props.showFrozenCol,
    },
  ].filter(({ visible }) => visible);
});

const isFieldEnabled = (field: 'frozenRow' | 'frozenCol') => {
  return !isEmpty(options.value[field]);
};

const getLeadingCount = (field: 'frozenRow' | 'frozenCol') => {
  return options.value[field]?.[0];
};

const getTrailingCount = (field: 'frozenRow' | 'frozenCol') => {
  return options.value[field]?.[1];
};

const onGroupChange = (
  field: 'frozenRow' | 'frozenCol',
  value: [number?, number?],
) => {
  options.value = {
    ...options.value,
    [field]: value,
  };
  emit('change', options.value);
};

const onCheckboxChange = (
  field: 'frozenRow' | 'frozenCol',
  checked: boolean,
) => {
  onGroupChange(field, checked ? [1, 1] : []);
};

const onLeadingChange = (
  field: 'frozenRow' | 'frozenCol',
  val: number | null,
) => {
  onGroupChange(field, [val ?? undefined, getTrailingCount(field)]);
};

const onTrailingChange = (
  field: 'frozenRow' | 'frozenCol',
  val: number | null,
) => {
  onGroupChange(field, [getLeadingCount(field), val ?? undefined]);
};
</script>

<template>
  <ResetGroup
    :title="title"
    :defaultCollapsed="defaultCollapsed"
    :class="PRE_CLASS"
    @reset="onResetClick"
  >
    <div v-if="showFrozenRowHeader" :class="`${PRE_CLASS}-container`">
      <Checkbox :checked="options.frozenRowHeader" @change="onRowHeaderChange">
        {{ i18n('冻结行头') }}
      </Checkbox>
    </div>
    <div
      v-for="config in BASE_FROZEN_CONFIG"
      :key="config.field"
      :class="`${PRE_CLASS}-container`"
    >
      <Checkbox
        :checked="isFieldEnabled(config.field)"
        @change="
          (e: CheckboxChangeEvent) =>
            onCheckboxChange(config.field, e.target.checked!)
        "
      >
        {{ i18n('冻结') }}{{ config.suffix }}
      </Checkbox>
      <span :class="`${PRE_CLASS}-container-group`">
        {{ i18n('冻结前') }}
        <FrozenInputNumber
          :disabled="!isFieldEnabled(config.field)"
          :value="getLeadingCount(config.field) ?? null"
          v-bind="inputNumberProps"
          @change="(val: number | null) => onLeadingChange(config.field, val)"
        />
        {{ config.suffix }}
      </span>
      <span :class="`${PRE_CLASS}-container-group`">
        {{ i18n('冻结后') }}
        <FrozenInputNumber
          :disabled="!isFieldEnabled(config.field)"
          :value="getTrailingCount(config.field) ?? null"
          v-bind="inputNumberProps"
          @change="(val: number | null) => onTrailingChange(config.field, val)"
        />
        {{ config.suffix }}
      </span>
    </div>
    <slot />
  </ResetGroup>
</template>

<style lang="less">
@import '@antv/s2/esm/styles/variables.less';

.@{s2-cls-prefix}-frozen-panel {
  width: 400px;

  &-container {
    display: flex;
    align-items: center;
    justify-content: space-between;

    &:not(:last-of-type) {
      margin-bottom: 6px;
    }

    &-group {
      color: rgba(0, 0, 0, 0.43);

      &:not(:last-of-type) {
        margin-right: 12px;
      }
    }

    .ant-checkbox-wrapper {
      margin-right: 50px;
      color: #535455;
    }

    .ant-input-number.@{s2-cls-prefix}-frozen-input-number {
      width: 50px;
      margin: 0 4px;
      border-radius: 4px;
    }
  }
}
</style>
