// packages/s2-react/src/components/tooltip/index.tsx
import { isEmpty } from 'lodash';
import React from 'react';
import { getTooltipDefaultOptions } from '@antv/s2';
import type {
  TooltipDetailListItem,
  TooltipOperatorOptions,
  TooltipSummaryOptions,
  TooltipNameTipsOptions,
  TooltipHeadInfo as TooltipHeadInfoType,
  TooltipInterpretationOptions,
} from '@antv/s2';
import { TooltipDetail } from './components/detail';
import { TooltipHead } from './components/head-info';
import { TooltipInfos } from './components/infos';
import { TooltipInterpretation } from './components/interpretation';
import { TooltipOperator } from './components/operator';
import { TooltipSimpleTips } from './components/simple-tips';
import { TooltipSummary } from './components/summary';
import { TooltipDescription } from './components/description';
import type { TooltipRenderProps } from './interface';

import './index.less';

export const TooltipComponent = (props: TooltipRenderProps) => {
  const { data, options, content, cell, onMounted } = props;

  const renderOperation = (
    operator:
      | TooltipOperatorOptions<React.ReactNode, React.ReactNode>
      | undefined,
    onlyShowOperator?: boolean,
  ) => {
    if (!operator) {
      return null;
    }

    return (
      <TooltipOperator
        {...operator}
        onClick={operator.onClick}
        onlyShowOperator={onlyShowOperator!}
        cell={cell!}
      />
    );
  };

  const renderNameTips = (nameTip: TooltipNameTipsOptions) => {
    const { name, tips } = nameTip || {};

    return <TooltipSimpleTips name={name} tips={tips} />;
  };

  const renderSummary = (summaries: TooltipSummaryOptions[] | undefined) =>
    !isEmpty(summaries) && <TooltipSummary summaries={summaries} />;

  const renderHeadInfo = (headInfo: TooltipHeadInfoType | undefined | null) => {
    const { cols = [], rows = [] } = headInfo || {};

    return (
      (!isEmpty(cols) || !isEmpty(rows)) && (
        <TooltipHead cols={cols} rows={rows} />
      )
    );
  };

  const renderDetail = (details: TooltipDetailListItem[] | null | undefined) =>
    !isEmpty(details) && <TooltipDetail list={details} />;

  const renderInfos = (infos: string | undefined) =>
    infos && <TooltipInfos infos={infos} />;

  const renderInterpretation = (
    interpretation: TooltipInterpretationOptions | undefined,
  ) => interpretation && <TooltipInterpretation {...interpretation} />;

  const renderDescription = (description: string | undefined) => (
    <TooltipDescription description={description} />
  );

  const renderContent = () => {
    const { operator, onlyShowOperator } = getTooltipDefaultOptions<
      React.ReactNode,
      React.ReactNode
    >(options);

    const {
      summaries,
      headInfo,
      details,
      interpretation,
      infos,
      tips,
      name,
      description,
    } = data || {};
    const nameTip: TooltipNameTipsOptions = { name, tips };

    if (onlyShowOperator) {
      return renderOperation(operator, true);
    }

    const DefaultContent = (
      <>
        {renderNameTips(nameTip)}
        {renderSummary(summaries)}
        {renderInterpretation(interpretation)}
        {renderHeadInfo(headInfo)}
        {renderDetail(details)}
        {renderInfos(infos)}
        {renderDescription(description)}
      </>
    );

    return (
      <span ref={onMounted}>
        {renderOperation(operator)}
        {content ?? DefaultContent}
      </span>
    );
  };

  return renderContent();
};

// packages/s2-vue/src/components/tooltip/index.vue
<script lang="ts">
import { getTooltipDefaultOptions } from '@antv/s2';
import { defineComponent } from 'vue';
import type { GetInitProps } from '../../interface';
import TooltipDescription from './components/description.vue';
import TooltipDetail from './components/detail.vue';
import TooltipHeadInfo from './components/head-info.vue';
import TooltipInfos from './components/infos.vue';
import TooltipInterpretation from './components/interpretation.vue';
import TooltipSimpleTips from './components/simple-tips.vue';
import TooltipSummary from './components/summary.vue';
import { TooltipOperator } from './components/operator';
import type { TooltipRenderProps } from './interface';

export default defineComponent({
  name: 'TooltipComponent',
  props: [
    'data',
    'options',
    'cell',
    'position',
    'event',
    'content',
  ] as unknown as GetInitProps<TooltipRenderProps>,
  setup(props) {
    const { operator, onlyShowOperator } = getTooltipDefaultOptions(
      props.options,
    );

    return {
      operator,
      onlyShowOperator,
    };
  },
  components: {
    TooltipDescription,
    TooltipDetail,
    TooltipHeadInfo,
    TooltipInfos,
    TooltipInterpretation,
    TooltipSimpleTips,
    TooltipSummary,
    TooltipOperator,
  },
});
</script>

<template>
  <template v-if="onlyShowOperator">
    <TooltipOperator
      :menu="operator?.menu"
      :onlyShowOperator="true"
      :cell="cell"
    />
  </template>
  <template v-else>
    <TooltipOperator
      :menu="operator?.menu"
      :onlyShowOperator="false"
      :cell="cell"
    />

    <template v-if="content">
      <slot name="content"></slot>
    </template>

    <template v-else>
      <TooltipSimpleTips :name="data?.name" :tips="data?.tips" />
      <TooltipSummary
        v-if="data?.summaries?.length"
        :summaries="data?.summaries"
      />
      <TooltipInterpretation
        v-if="data?.interpretation"
        :name="data?.interpretation?.name"
        :icon="data?.interpretation?.icon"
        :text="data?.interpretation?.text"
        :content="data?.interpretation?.content"
      />
      <TooltipHeadInfo
        :rows="data?.headInfo?.rows || []"
        :cols="data?.headInfo?.cols || []"
      />
      <TooltipDetail :list="data?.details || []" />
      <TooltipInfos v-if="data?.infos" :infos="data?.infos" />
      <TooltipDescription :description="data?.description" />
    </template>
  </template>
</template>

<style lang="less">
@import '@antv/s2/esm/shared/styles/tooltip/index.less';
</style>
