// packages/s2-vue/src/components-extra/common/reset-group/ResetGroup.vue
<script setup lang="ts">
import { CaretRightOutlined } from '@ant-design/icons-vue';
import { S2_PREFIX_CLS } from '@antv/s2';
import { Collapse, CollapsePanel } from 'ant-design-vue';
import { computed, ref } from 'vue';
import { ResetButton } from '../reset-button';

const ACTIVE_KEY = 'RESET_GROUP';
const PRE_CLASS = `${S2_PREFIX_CLS}-reset-group`;

const props = withDefaults(
  defineProps<{
    title?: string;
    defaultCollapsed?: boolean;
    class?: string;
  }>(),
  {
    title: '',
    defaultCollapsed: false,
    class: '',
  },
);

const emit = defineEmits<{
  reset: [];
}>();

const activeKey = ref(props.defaultCollapsed ? [] : [ACTIVE_KEY]);

const classNames = computed(() => {
  return [PRE_CLASS, props.class].filter(Boolean).join(' ');
});

const handleResetClick = (e: MouseEvent) => {
  e.stopPropagation();
  emit('reset');
};
</script>

<template>
  <Collapse v-model:activeKey="activeKey" :bordered="false" :class="classNames">
    <template #expandIcon="{ isActive }">
      <CaretRightOutlined :rotate="isActive ? 90 : 0" />
    </template>
    <CollapsePanel
      :key="ACTIVE_KEY"
      :header="title"
      :class="`${PRE_CLASS}-panel`"
    >
      <template #extra>
        <ResetButton @click="handleResetClick" />
      </template>
      <slot />
    </CollapsePanel>
  </Collapse>
</template>

<style lang="less">
@import '@antv/s2/esm/styles/variables.less';

.@{s2-cls-prefix}-reset-group {
  width: 340px;
}
</style>

// packages/s2-react-components/src/components/common/reset-group/index.tsx
import { CaretRightOutlined } from '@ant-design/icons';
import { S2_PREFIX_CLS } from '@antv/s2';
import { Collapse } from 'antd';
import cls from 'classnames';
import React from 'react';
import { ResetButton } from '../reset-button';
import './index.less';
import type { ResetGroupProps } from './interface';

const ACTIVE_KEY = 'RESET_GROUP';
const PRE_CLASS = `${S2_PREFIX_CLS}-reset-group`;

export const ResetGroup: React.FC<ResetGroupProps> = React.memo((props) => {
  const {
    title,
    defaultCollapsed = false,
    style,
    className,
    onResetClick,
    children,
  } = props;

  return (
    <Collapse
      bordered={false}
      defaultActiveKey={!defaultCollapsed ? ACTIVE_KEY : ''}
      className={cls(PRE_CLASS, className)}
      expandIcon={({ isActive }) => (
        <CaretRightOutlined rotate={isActive ? 90 : 0} />
      )}
      style={style}
    >
      <Collapse.Panel
        key={ACTIVE_KEY}
        header={title}
        className={`${PRE_CLASS}-panel`}
        extra={
          <ResetButton
            onClick={(e) => {
              e.stopPropagation();
              onResetClick?.();
            }}
          />
        }
      >
        {children}
      </Collapse.Panel>
    </Collapse>
  );
});

ResetGroup.displayName = 'ResetGroup';
