// packages/s2-core/src/ui/tooltip/components/operator/index.tsx
import { Menu, Dropdown } from 'antd';
import { isEmpty, map, size } from 'lodash';
import React from 'react';
import { Icon } from '../icon';
import { TOOLTIP_PREFIX_CLS } from '@/common/constant/tooltip';
import {
  TooltipOperatorMenu,
  TooltipOperatorOptions,
} from '@/common/interface';
import './index.less';

/**
 * tooltip menu
 *  - UI
 *  - actions
 *    delay 300ms show
 */

export const TooltipOperator = (props: TooltipOperatorOptions) => {
  const { menus, onClick, onlyMenu } = props;

  const onMenuClick = (e) => {
    const { key } = e;
    onClick(key, e);
  };

  const renderTitle = (text: string, icon) => {
    return (
      <span>
        <Icon icon={icon} className={`${TOOLTIP_PREFIX_CLS}-operator-icon`} />
        {text}
      </span>
    );
  };

  const renderMenu = (menu: TooltipOperatorMenu) => {
    const { id, icon, text, children } = menu;

    if (size(children)) {
      return (
        <Menu.SubMenu
          title={renderTitle(text, icon)}
          key={id}
          popupClassName={`${TOOLTIP_PREFIX_CLS}-operator-submenu-popup`}
        >
          {map(children, (subMenu: TooltipOperatorMenu) => renderMenu(subMenu))}
        </Menu.SubMenu>
      );
    }

    return (
      <Menu.Item title={text} key={id}>
        {renderTitle(text, icon)}
      </Menu.Item>
    );
  };

  const renderMenus = () => {
    if (onlyMenu) {
      return (
        <Menu
          className={`${TOOLTIP_PREFIX_CLS}-operator-menus`}
          onClick={onMenuClick}
        >
          {map(menus, (menu: TooltipOperatorMenu) => renderMenu(menu))}
        </Menu>
      );
    }
    return map(menus, (menu: TooltipOperatorMenu) => {
      const { id, icon, text, children } = menu;

      const menuRender = size(children) ? (
        <Menu
          className={`${TOOLTIP_PREFIX_CLS}-operator-menus`}
          key={id}
          onClick={onMenuClick}
        >
          {map(children, (menu: TooltipOperatorMenu) => renderMenu(menu))}
        </Menu>
      ) : (
        <></>
      );

      return (
        <Dropdown overlay={menuRender}>{renderTitle(text, icon)}</Dropdown>
      );
    });
  };

  return (
    !isEmpty(menus) && (
      <div className={`${TOOLTIP_PREFIX_CLS}-operator`}>{renderMenus()}</div>
    )
  );
};

// packages/s2-vue/src/components/tooltip/components/operator/index.vue
<script lang="ts">
import { TOOLTIP_PREFIX_CLS } from '@antv/s2';
import type { TooltipOperatorProps as BaseTooltipOperatorProps } from '@antv/s2-shared';
import { Menu, Dropdown, type MenuProps } from 'ant-design-vue';
import { defineComponent } from 'vue';
import type { GetInitProps } from '../../../../interface';
import TooltipOperatorTitle from './title.vue';
import TooltipOperatorMenu from './menu.vue';

interface TooltipOperatorProps extends BaseTooltipOperatorProps {
  onClick?: MenuProps['onClick'];
}

export default defineComponent({
  name: 'TooltipOperator',
  props: [
    'menus',
    'onlyMenu',
    'onClick',
    'cell',
  ] as unknown as GetInitProps<TooltipOperatorProps>,
  setup() {
    return {
      TOOLTIP_PREFIX_CLS,
    };
  },
  components: {
    Menu,
    Dropdown,
    TooltipOperatorTitle,
    TooltipOperatorMenu,
  },
});
</script>

<template>
  <div :class="`${TOOLTIP_PREFIX_CLS}-operator`">
    <template v-if="onlyMenu">
      <Menu :class="`${TOOLTIP_PREFIX_CLS}-operator-menus`" @click="onClick">
        <template v-for="menu in menus" :key="menu.key">
          <TooltipOperatorMenu :menu="menu" :cell="cell" />
        </template>
      </Menu>
    </template>
    <template v-else>
      <template v-for="menu in menus" :key="menu.key">
        <Dropdown :class="`${TOOLTIP_PREFIX_CLS}-operator-dropdown`">
          <TooltipOperatorTitle :menu="menu" @click="menu.onClick?.(cell)" />
          <template #overlay>
            <Menu
              :class="`${TOOLTIP_PREFIX_CLS}-operator-menus`"
              @click="onClick"
              v-if="menu?.children?.length"
            >
              <template v-for="menu in menus" :key="menu.key">
                <TooltipOperatorMenu :menu="menu" :cell="cell" />
              </template>
            </Menu>
          </template>
        </Dropdown>
      </template>
    </template>
  </div>
</template>

<style lang="less">
@import '@antv/s2-shared/src/styles/tooltip/operator.less';
</style>
