// packages/s2-react/src/components/sheets/index.tsx
import type { SpreadSheet } from '@antv/s2';
import React from 'react';
import { SpreadSheetContext } from '../../context/SpreadSheetContext';
import { ConfigProvider } from '../config-provider';
import { EditableSheet } from './editable-sheet';
import { GridAnalysisSheet } from './grid-analysis-sheet';
import type { SheetComponentsProps } from './interface';
import { PivotSheet } from './pivot-sheet';
import { StrategySheet } from './strategy-sheet';
import { TableSheet } from './table-sheet';
import { ChartSheet } from './chart-sheet';

const Sheet = React.forwardRef<SpreadSheet, SheetComponentsProps>(
  (props, ref) => {
    const { sheetType, themeCfg } = props;

    const [s2Instance, setS2Instance] = React.useState<SpreadSheet | null>(
      null,
    );
    const sheetProps = React.useMemo<SheetComponentsProps>(() => {
      return {
        ...props,
        onMounted: (instance) => {
          if (ref) {
            (ref as React.MutableRefObject<SpreadSheet>).current = instance;
          }

          setS2Instance(instance);
          props.onMounted?.(instance);
        },
      };
    }, [props, ref]);

    const CurrentSheet = React.useMemo(() => {
      switch (sheetType) {
        case 'table':
          return <TableSheet {...sheetProps} />;
        case 'chart':
          return <ChartSheet {...sheetProps} />;
        case 'gridAnalysis':
          return <GridAnalysisSheet {...sheetProps} />;
        case 'strategy':
          return <StrategySheet {...sheetProps} />;
        case 'editable':
          return <EditableSheet {...sheetProps} />;
        default:
          return <PivotSheet {...sheetProps} />;
      }
    }, [sheetType, sheetProps]);

    return (
      <SpreadSheetContext.Provider value={s2Instance!}>
        <ConfigProvider themeName={themeCfg?.name}>
          {CurrentSheet}
        </ConfigProvider>
      </SpreadSheetContext.Provider>
    );
  },
);

export const SheetComponent: React.ForwardRefExoticComponent<
  SheetComponentsProps & React.RefAttributes<SpreadSheet>
> = React.memo(Sheet);

SheetComponent.displayName = 'SheetComponent';

// packages/s2-vue/src/components/sheets/index.vue
<script lang="ts">
import type { SheetType } from '@antv/s2';
import { computed, defineComponent } from 'vue';
import { useExpose } from '../../hooks/useExpose';
import type { BaseSheetInitEmits, BaseSheetInitProps } from '../../interface';
import ChartSheet from './chart-sheet.vue';
import EditableSheet from './editable-sheet.vue';
import GridAnalysisSheet from './grid-analysis-sheet/index.vue';
import PivotChartSheet from './pivot-chart-sheet.vue';
import PivotSheet from './pivot-sheet.vue';
import StrategySheet from './strategy-sheet/index.vue';
import TableSheet from './table-sheet.vue';

export default defineComponent({
  name: 'Sheet',
  props: [] as unknown as BaseSheetInitProps,
  emits: [] as unknown as BaseSheetInitEmits,
  setup(props, ctx) {
    const s2Ref = useExpose(ctx.expose);

    const sheetType = computed(() => {
      const type = ctx.attrs['sheetType'] as SheetType;

      switch (type) {
        case 'table':
          return TableSheet;
        case 'editable':
          return EditableSheet;
        case 'chart':
          return ChartSheet;
        case 'gridAnalysis':
          return GridAnalysisSheet;
        case 'strategy':
          return StrategySheet;
        case 'pivotChart':
          return PivotChartSheet;
        default:
          return PivotSheet;
      }
    });

    return { s2Ref, sheetType };
  },
  components: {
    PivotSheet,
    TableSheet,
    EditableSheet,
    ChartSheet,
    GridAnalysisSheet,
    StrategySheet,
    PivotChartSheet,
  },
});
</script>
<template>
  <component :is="sheetType" ref="s2Ref" />
</template>
