// packages/s2-react/src/components/sheets/pivot-sheet/index.tsx
import { getTooltipOptions, SpreadSheet } from '@antv/s2';
import { useLatest } from 'ahooks';
import { isEmpty, isObject } from 'lodash';
import React from 'react';
import { usePivotSheetUpdate } from '../../../hooks';
import {
  ActionIconCallback,
  buildDrillDownOptions,
  handleDrillDown,
} from '../../../utils';
import { DrillDown } from '../../drill-down';
import { BaseSheet } from '../base-sheet';
import { SheetComponentsProps } from '../interface';

export const PivotSheet: React.FC<SheetComponentsProps> = React.memo(
  (props) => {
    const { options: pivotOptions, ...restProps } = props;
    const { dataCfg, partDrillDown } = restProps;

    const s2Ref = React.useRef<SpreadSheet>();
    const [drillFields, setDrillFields] = React.useState<string[]>([]);

    const onDrillDownIconClick = useLatest<ActionIconCallback>(
      ({ sheetInstance, cacheDrillFields, disabledFields, event }) => {
        const content = (
          <DrillDown
            {...partDrillDown?.drillConfig}
            setDrillFields={setDrillFields}
            drillFields={cacheDrillFields}
            disabledFields={disabledFields}
          />
        );

        if (event) {
          const { showTooltip } = getTooltipOptions(sheetInstance, event);
          if (!showTooltip) {
            return;
          }
          sheetInstance.showTooltip<React.ReactNode>({
            position: {
              x: event.clientX,
              y: event.clientY,
            },
            content,
          });
        }
      },
    );

    /** 基于 props.options 来构造新的 options 传递给 base-sheet */
    const options = React.useMemo(() => {
      return buildDrillDownOptions(pivotOptions, partDrillDown, (params) =>
        onDrillDownIconClick.current(params),
      );
    }, [pivotOptions, partDrillDown, onDrillDownIconClick]);

    /**
     * 清空下钻信息
     * @param rowId 不传表示全部清空
     */
    const clearDrillDownInfo = (rowId?: string) => {
      s2Ref.current?.clearDrillDownData(rowId);
    };

    /**
     * 加载或清除下钻数据
     * 仅由 drillFields 驱动
     */
    React.useEffect(() => {
      s2Ref.current?.hideTooltip();
      if (isEmpty(drillFields)) {
        clearDrillDownInfo(s2Ref.current.store.get('drillDownNode')?.id);
      } else {
        // 执行下钻
        handleDrillDown({
          rows: dataCfg.fields.rows,
          drillFields,
          fetchData: partDrillDown?.fetchData,
          drillItemsNum: partDrillDown?.drillItemsNum,
          spreadsheet: s2Ref.current,
        });
      }
      // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [drillFields]);

    React.useEffect(() => {
      if (!isObject(partDrillDown?.clearDrillDown)) {
        return;
      }
      clearDrillDownInfo(partDrillDown?.clearDrillDown?.rowId);
    }, [partDrillDown?.clearDrillDown]);

    /**
     * 控制交叉表 render
     */
    const onSheetUpdate = usePivotSheetUpdate(partDrillDown);

    return (
      <BaseSheet
        {...restProps}
        options={options}
        onSheetUpdate={onSheetUpdate}
        ref={s2Ref}
      />
    );
  },
);

PivotSheet.displayName = 'PivotSheet';

// packages/s2-vue/src/components/sheets/pivot-sheet.vue
<script lang="ts">
import { computed, defineComponent, ref, toRefs, createVNode } from 'vue';
import { isEmpty } from 'lodash';
import { buildDrillDownOptions, handleDrillDown } from '@antv/s2-shared';
import type { SpreadSheet, S2Options } from '@antv/s2';
import type { PartDrillDown, ActionIconCallbackParams } from '@antv/s2-shared';
import { useExpose } from '../../hooks/useExpose';
import {
  initBaseSheetEmits,
  initBaseSheetProps,
} from '../../utils/initPropAndEmits';
import DrillDown from '../drill-down/index.vue';
import BaseSheet from './base-sheet.vue';

export default defineComponent({
  name: 'PivotSheet',
  props: initBaseSheetProps(),
  emits: initBaseSheetEmits(),
  setup(props, ctx) {
    const s2Ref = useExpose(ctx.expose);
    const { options: pivotOptions } = toRefs(props);
    const { dataCfg, partDrillDown } = toRefs(props);
    // 被下钻的 field
    const drillFields = ref<string[]>([]);

    // 执行下钻操作
    const setDrillFields = (fields: string[]) => {
      const instance = s2Ref?.value?.instance;
      drillFields.value = fields;
      instance?.hideTooltip();
      if (isEmpty(fields)) {
        instance?.clearDrillDownData(instance?.store.get('drillDownNode')?.id);
      } else {
        // 执行下钻
        handleDrillDown({
          rows: dataCfg.value?.fields.rows ?? [],
          drillFields: fields,
          fetchData: partDrillDown.value?.fetchData,
          drillItemsNum: partDrillDown.value?.drillItemsNum,
          spreadsheet: instance as SpreadSheet,
        });
      }
    };

    /**
     * 点击下钻后，下钻组件的出现
     */
    const onDrillDownIconClick = (params: ActionIconCallbackParams) => {
      const { event, disabledFields } = params;
      if (event) {
        const instance = s2Ref?.value?.instance;
        const drillDownNode = createVNode(DrillDown, {
          ...partDrillDown.value?.drillConfig,
          setDrillFields,
          drillFields: drillFields.value,
          disabledFields,
        });

        // 将下钻设置为 tooltip 的 content 进行展示
        instance?.showTooltip({
          position: {
            x: event.clientX,
            y: event.clientY,
          },
          event,
          content: drillDownNode,
        });
      }
    };

    // 展示下钻icon
    const options = computed(() =>
      buildDrillDownOptions(
        pivotOptions.value as S2Options,
        partDrillDown.value as PartDrillDown,
        (params) => onDrillDownIconClick(params),
      ),
    ) as S2Options;

    return {
      s2Ref,
      options,
    };
  },
  components: {
    BaseSheet,
  },
});
</script>

<template>
  <BaseSheet v-bind="$props" ref="s2Ref" :options="options" />
</template>
