// packages/s2-react/src/components/sheets/table-sheet/index.tsx
import React, { memo, useEffect } from 'react';
import { SpreadSheet } from '@antv/s2';
import { BaseSheet } from '../base-sheet';
import { SheetComponentsProps } from '@/components/sheets/interface';

export const TableSheet: React.FC<SheetComponentsProps> = memo((props) => {
  const { options } = props;
  const s2Ref = React.useRef<SpreadSheet>();
  useEffect(() => {
    s2Ref.current?.setOptions({ interaction: { hiddenColumnFields: [] } });
    s2Ref.current?.interaction.hideColumns(
      options.interaction?.hiddenColumnFields,
    );
  }, [options.interaction?.hiddenColumnFields, s2Ref]);

  return <BaseSheet {...props} ref={s2Ref} />;
});

TableSheet.displayName = 'TableSheet';

// packages/s2-vue/src/components/sheets/table-sheet.vue
<script lang="ts">
import type { SpreadSheet } from '@antv/s2';
import { defineComponent, shallowRef } from 'vue';
import type { BaseSheetInitEmits, BaseSheetInitProps } from '../../interface';
import BaseSheet from './base-sheet.vue';

export default defineComponent({
  name: 'TableSheet',
  props: [] as unknown as BaseSheetInitProps,
  emits: [] as unknown as BaseSheetInitEmits,
  setup(props, ctx) {
    const s2Ref = shallowRef<{ instance: SpreadSheet }>();

    ctx.expose({
      get instance() {
        return s2Ref.value?.instance;
      },
    });

    return { s2Ref };
  },
  components: {
    BaseSheet,
  },
});
</script>
<template>
  <BaseSheet ref="s2Ref" />
</template>
