// packages/s2-vue/src/components/tooltip/components/interpretation.vue
<script lang="ts">
import {
  TOOLTIP_PREFIX_CLS,
  type TooltipInterpretationOptions,
} from '@antv/s2';
import { defineComponent } from 'vue';
import type { GetInitProps } from '../../../interface';
import TooltipIcon from './icon.vue';

export default defineComponent({
  name: 'TooltipInterpretation',
  props: [
    'name',
    'icon',
    'text',
    'content',
  ] as unknown as GetInitProps<TooltipInterpretationOptions>,
  setup() {
    return {
      TOOLTIP_PREFIX_CLS,
    };
  },
  components: {
    TooltipIcon,
  },
});
</script>

<template>
  <div :class="`${TOOLTIP_PREFIX_CLS}-interpretation`">
    <div :class="`${TOOLTIP_PREFIX_CLS}-interpretation-head`">
      <TooltipIcon
        :icon="icon"
        :class="`${TOOLTIP_PREFIX_CLS}-interpretation-icon`"
      />
      <span v-if="name" :class="`${TOOLTIP_PREFIX_CLS}-interpretation-name`">
        {{ name }}
      </span>
    </div>
    <div v-if="text">{{ text }}</div>
    <slot v-if="content" name="content">
      <component v-if="typeof content === 'object'" :is="content" />
      <span v-else>{{ content }}</span>
    </slot>
  </div>
</template>

<style lang="less"></style>

// packages/s2-react/src/components/tooltip/components/interpretation.tsx
import React from 'react';
import { TooltipInterpretationOptions, TOOLTIP_PREFIX_CLS } from '@antv/s2';
import { TooltipIcon } from './icon';
import { ReactElement } from '@/common/react-element';

export const TooltipInterpretation: React.FC<TooltipInterpretationOptions> = (
  props,
) => {
  const { name, icon, text, render } = props;

  const renderName = () => {
    return (
      name && (
        <span className={`${TOOLTIP_PREFIX_CLS}-interpretation-name`}>
          {name}
        </span>
      )
    );
  };

  const renderText = () => {
    return text && <div>{text}</div>;
  };

  const renderElement = () => {
    return <ReactElement content={render} />;
  };

  return (
    <div className={`${TOOLTIP_PREFIX_CLS}-interpretation`}>
      <div className={`${TOOLTIP_PREFIX_CLS}-interpretation-head`}>
        <TooltipIcon
          icon={icon}
          className={`${TOOLTIP_PREFIX_CLS}-interpretation-icon`}
        />
        {renderName()}
      </div>
      {renderText()}
      {renderElement()}
    </div>
  );
};
