// packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/data-cell-tooltip.tsx
import {
  i18n,
  getEmptyPlaceholder,
  isUpDataValue,
  type MultiData,
  type SimpleData,
  type ViewMeta,
  isUnchangedValue,
} from '@antv/s2';
import cls from 'classnames';
import { first, get, isEmpty, isFunction, isNil } from 'lodash';
import React from 'react';
import { getStrategySheetTooltipClsName as tooltipCls } from '@antv/s2-shared';
import type { CustomTooltipProps } from './interface';

import './index.less';

export const StrategySheetDataCellTooltip: React.FC<CustomTooltipProps> = ({
  cell,
  label,
  showOriginalValue: showOriginalValueFromTooltip,
  renderDerivedValue,
}) => {
  const meta = cell.getMeta() as ViewMeta;
  const { spreadsheet } = meta;
  const metaFieldValue = meta?.fieldValue as MultiData<SimpleData[][]>;

  const rowDescription = spreadsheet.dataSet.getCustomFieldDescription(cell);
  const defaultRowName = spreadsheet.dataSet.getCustomRowFieldName(cell);
  const customLabel = isFunction(label) ? label(cell, defaultRowName) : label;
  const rowName = customLabel ?? defaultRowName;
  const colLeafNode = spreadsheet.facet.getColLeafNodeByIndex(meta.colIndex);

  const [, ...derivedLabels] = React.useMemo(() => {
    try {
      return JSON.parse(colLeafNode?.value!);
    } catch {
      return [];
    }
  }, [colLeafNode?.value]);

  const { placeholder, style } = spreadsheet.options;
  const valuesCfg = style?.dataCell?.valuesCfg;

  const [value, ...derivedValues] = first(metaFieldValue?.values) || [
    metaFieldValue,
  ];
  const [originalValue, ...derivedOriginalValues] = first(
    get(metaFieldValue, valuesCfg?.originalValueField!) as SimpleData[][],
  ) || [value];

  const emptyPlaceholder = getEmptyPlaceholder(meta, placeholder);
  const showOriginalValue =
    valuesCfg?.showOriginalValue || showOriginalValueFromTooltip;

  return (
    <div className={cls(tooltipCls(), tooltipCls('data'))}>
      <div className={tooltipCls('header')}>
        <span className={'header-label'}>{rowName}</span>
        <span>{(value as React.ReactNode) ?? emptyPlaceholder}</span>
      </div>
      {showOriginalValue && (
        <div className={tooltipCls('original-value')}>
          {isNil(originalValue)
            ? emptyPlaceholder
            : (originalValue as React.ReactNode)}
        </div>
      )}
      {!isEmpty(derivedValues) && (
        <>
          <div className={tooltipCls('divider')} />
          <ul className={tooltipCls('derived-values')}>
            {(derivedValues as SimpleData[]).map((derivedValue, i) => {
              const isUnchanged = isUnchangedValue(
                derivedValue,
                value as SimpleData,
              );
              const isUp = !isUnchanged && isUpDataValue(derivedValue);
              const isDown = !isUnchanged && !isUp;
              const originalDerivedValue = derivedOriginalValues[
                i
              ] as SimpleData;

              return (
                <li className="derived-value-item" key={i}>
                  <span className="derived-value-label">
                    {derivedLabels[i]}
                  </span>
                  <span
                    className={cls('derived-value-group', {
                      'derived-value-trend-up': isUp,
                      'derived-value-trend-down': isDown,
                    })}
                  >
                    {!isUnchanged && (
                      <span className="derived-value-trend-icon"></span>
                    )}
                    {renderDerivedValue?.(
                      derivedValue,
                      originalDerivedValue,
                      cell,
                    ) ?? (
                      <span className="derived-value-content">
                        {derivedValue ?? emptyPlaceholder}
                      </span>
                    )}
                  </span>
                </li>
              );
            })}
          </ul>
        </>
      )}
      {rowDescription && (
        <div className={tooltipCls('description')}>
          <span className={tooltipCls('description-label')}>
            {i18n('说明')}
          </span>
          <span className={tooltipCls('description-text')}>
            {rowDescription}
          </span>
        </div>
      )}
    </div>
  );
};

StrategySheetDataCellTooltip.defaultProps = {
  showOriginalValue: false,
};

// packages/s2-vue/src/components/sheets/strategy-sheet/custom-tooltip/data-cell-tooltip.vue
<script lang="ts">
import type { MultiData, SimpleData, ViewMeta } from '@antv/s2';
import {
  getEmptyPlaceholder,
  i18n,
  isUnchangedValue,
  isUpDataValue,
  getStrategySheetTooltipClsName as tooltipCls,
} from '@antv/s2';
import { first, get, isEmpty, isFunction, isNil } from 'lodash';
import { computed, defineComponent, type PropType } from 'vue';
import type { CustomTooltipProps } from './interface';

export default defineComponent({
  name: 'StrategySheetDataCellTooltip',
  props: {
    cell: {
      type: Object as PropType<CustomTooltipProps['cell']>,
      required: true,
    },
    label: {
      type: [Object, Function] as PropType<CustomTooltipProps['label']>,
      default: undefined,
    },
    showOriginalValue: {
      type: Boolean,
      default: false,
    },
    renderDerivedValue: {
      type: Function as PropType<CustomTooltipProps['renderDerivedValue']>,
      default: undefined,
    },
  },
  setup(props) {
    const meta = computed(() => props.cell.getMeta() as ViewMeta);
    const spreadsheet = computed(() => meta.value.spreadsheet);
    const metaFieldValue = computed(
      () => meta.value?.fieldValue as MultiData<SimpleData[][]>,
    );

    const rowDescription = computed(() =>
      spreadsheet.value.dataSet.getCustomFieldDescription(props.cell),
    );

    const rowName = computed(() => {
      const defaultRowName = spreadsheet.value.dataSet.getCustomRowFieldName(
        props.cell,
      );
      const customLabel = isFunction(props.label)
        ? props.label(props.cell, defaultRowName)
        : props.label;

      return customLabel ?? defaultRowName;
    });

    const colLeafNode = computed(() =>
      spreadsheet.value.facet.getColLeafNodeByIndex(meta.value.colIndex),
    );

    const derivedLabels = computed(() => {
      try {
        const [, ...labels] = JSON.parse(colLeafNode.value?.value!);

        return labels;
      } catch {
        return [];
      }
    });

    const valuesCfg = computed(
      () => spreadsheet.value.options.style?.dataCell?.valuesCfg,
    );

    const values = computed(() => {
      const firstValues = first(metaFieldValue.value?.values) || [
        metaFieldValue.value,
      ];

      return {
        value: firstValues[0],
        derivedValues: firstValues.slice(1) as SimpleData[],
      };
    });

    const originalValues = computed(() => {
      const originalValuesField = get(
        metaFieldValue.value,
        valuesCfg.value?.originalValueField!,
      ) as SimpleData[][];
      const firstOriginal = first(originalValuesField) || [values.value.value];

      return {
        originalValue: firstOriginal[0],
        derivedOriginalValues: firstOriginal.slice(1) as SimpleData[],
      };
    });

    const emptyPlaceholder = computed(() =>
      getEmptyPlaceholder(meta.value, spreadsheet.value.options.placeholder),
    );

    const shouldShowOriginalValue = computed(
      () => valuesCfg.value?.showOriginalValue || props.showOriginalValue,
    );

    const getDerivedValueInfo = (derivedValue: SimpleData, index: number) => {
      const isUnchanged = isUnchangedValue(
        derivedValue,
        values.value.value as SimpleData,
      );
      const isUp = !isUnchanged && isUpDataValue(derivedValue);
      const isDown = !isUnchanged && !isUp;
      const originalDerivedValue =
        originalValues.value.derivedOriginalValues[index];

      return { isUnchanged, isUp, isDown, originalDerivedValue };
    };

    return {
      tooltipCls,
      i18n,
      isEmpty,
      isNil,
      rowName,
      rowDescription,
      values,
      originalValues,
      derivedLabels,
      emptyPlaceholder,
      shouldShowOriginalValue,
      getDerivedValueInfo,
    };
  },
});
</script>

<template>
  <div :class="[tooltipCls(), tooltipCls('data')]">
    <div :class="tooltipCls('header')">
      <span class="header-label">{{ rowName }}</span>
      <span>{{ values.value ?? emptyPlaceholder }}</span>
    </div>

    <div v-if="shouldShowOriginalValue" :class="tooltipCls('original-value')">
      {{
        isNil(originalValues.originalValue)
          ? emptyPlaceholder
          : originalValues.originalValue
      }}
    </div>

    <template v-if="!isEmpty(values.derivedValues)">
      <div :class="tooltipCls('divider')" />
      <ul :class="tooltipCls('derived-values')">
        <li
          v-for="(derivedValue, i) in values.derivedValues"
          :key="i"
          class="derived-value-item"
        >
          <span class="derived-value-label">{{ derivedLabels[i] }}</span>
          <span
            :class="[
              'derived-value-group',
              {
                'derived-value-trend-up': getDerivedValueInfo(derivedValue, i)
                  .isUp,
                'derived-value-trend-down': getDerivedValueInfo(derivedValue, i)
                  .isDown,
              },
            ]"
          >
            <span
              v-if="!getDerivedValueInfo(derivedValue, i).isUnchanged"
              class="derived-value-trend-icon"
            />
            <template
              v-if="
                renderDerivedValue?.(
                  derivedValue,
                  getDerivedValueInfo(derivedValue, i).originalDerivedValue,
                  cell,
                )
              "
            >
              {{
                renderDerivedValue(
                  derivedValue,
                  getDerivedValueInfo(derivedValue, i).originalDerivedValue,
                  cell,
                )
              }}
            </template>
            <span v-else class="derived-value-content">
              {{ derivedValue ?? emptyPlaceholder }}
            </span>
          </span>
        </li>
      </ul>
    </template>

    <div v-if="rowDescription" :class="tooltipCls('description')">
      <span :class="tooltipCls('description-label')">{{ i18n('说明') }}</span>
      <span :class="tooltipCls('description-text')">{{ rowDescription }}</span>
    </div>
  </div>
</template>

<style lang="less">
@import './index.less';
</style>
