// packages/s2-react-components/src/components/analysis/switcher/switcher.tsx
import { SwapOutlined } from '@ant-design/icons';
import { i18n } from '@antv/s2';
import { Button, Popover } from 'antd';
import cls from 'classnames';
import React from 'react';
import { SwitcherContent } from './content';
import './index.less';
import type { SwitcherProps } from './interface';
import { getSwitcherClassName } from './util';

export const Switcher: React.FC<SwitcherProps> = React.memo(
  ({ title, popover, disabled, ...otherProps }) => {
    const [visible, setVisible] = React.useState(false);
    const onToggleVisible = () => {
      setVisible((prev) => !prev);
    };

    return (
      <Popover
        open={!disabled && visible}
        content={
          <SwitcherContent {...otherProps} onToggleVisible={onToggleVisible} />
        }
        onOpenChange={onToggleVisible}
        trigger="click"
        placement="bottomLeft"
        destroyTooltipOnHide
        {...popover}
        overlayClassName={cls(
          getSwitcherClassName('switcher-overlay'),
          popover?.overlayClassName,
        )}
      >
        {React.isValidElement(title) ? (
          title
        ) : (
          <Button
            className={getSwitcherClassName('entry-button')}
            size="small"
            disabled={disabled}
            icon={<SwapOutlined rotate={90} />}
          >
            {title || i18n('行列切换')}
          </Button>
        )}
      </Popover>
    );
  },
);

Switcher.displayName = 'Switcher';

// packages/s2-vue/src/components-extra/switcher/Switcher.vue
<script setup lang="ts">
import { SwapOutlined } from '@ant-design/icons-vue';
import { i18n } from '@antv/s2';
import { Button, Popover } from 'ant-design-vue';
import { computed, h, ref } from 'vue';
import SwitcherContent from './SwitcherContent.vue';
import type { SwitcherProps, SwitcherResult } from './interface';
import { getSwitcherClassName } from './util';

const props = withDefaults(defineProps<SwitcherProps>(), {
  disabled: false,
});

const emit = defineEmits<{
  (e: 'submit', result: SwitcherResult): void;
}>();

const visible = ref(false);

const onToggleVisible = (open?: boolean) => {
  if (typeof open === 'boolean') {
    visible.value = open;
  } else {
    visible.value = !visible.value;
  }
};

const onSubmit = (result: SwitcherResult) => {
  emit('submit', result);
};

const overlayClassName = computed(() => {
  return (
    props.popover?.overlayClassName
      ? [
          getSwitcherClassName('switcher-overlay'),
          props.popover.overlayClassName,
        ]
      : [getSwitcherClassName('switcher-overlay')]
  ).join(' ');
});

const defaultTitle = computed(() => props.title || i18n('行列切换'));

// Helper to render icon
const renderIcon = () => {
  if (props.icon) {
    return props.icon;
  }

  // Rotate SwapOutlined 90 deg
  return h(SwapOutlined, { rotate: 90 });
};
</script>

<template>
  <Popover
    :open="!disabled && visible"
    trigger="click"
    placement="bottomLeft"
    :destroyTooltipOnHide="true"
    :overlayClassName="overlayClassName"
    v-bind="popover"
    @openChange="onToggleVisible"
  >
    <template #content>
      <SwitcherContent
        v-bind="props"
        @toggle-visible="() => onToggleVisible(false)"
        @submit="onSubmit"
      />
    </template>

    <slot>
      <Button
        :class="getSwitcherClassName('entry-button')"
        size="small"
        :disabled="disabled"
      >
        <template #icon>
          <component :is="renderIcon()" />
        </template>
        {{ defaultTitle }}
      </Button>
    </slot>
  </Popover>
</template>

<style lang="less">
@import './index.less';
</style>
