// packages/s2-vue/src/components-extra/common/reset-button/ResetButton.vue
<script setup lang="ts">
import { ReloadOutlined } from '@ant-design/icons-vue';
import { S2_PREFIX_CLS, i18n } from '@antv/s2';

const PRE_CLASS = `${S2_PREFIX_CLS}-reset-btn`;

withDefaults(
  defineProps<{
    title?: string;
  }>(),
  {
    title: () => i18n('重置'),
  },
);

const emit = defineEmits<{
  click: [event: MouseEvent];
}>();

const handleClick = (event: MouseEvent) => {
  emit('click', event);
};
</script>

<template>
  <span :class="PRE_CLASS" @click="handleClick">
    <ReloadOutlined :class="`${PRE_CLASS}-icon`" />
    <span :class="`${PRE_CLASS}-text`">{{ title }}</span>
  </span>
</template>

<style lang="less">
@import '@antv/s2/esm/styles/variables.less';

.@{s2-cls-prefix}-reset-btn {
  color: #3572f9;
  cursor: pointer;
  padding-left: 8px;

  &-text {
    margin-left: 4px;
  }
}
</style>

// packages/s2-react-components/src/components/common/reset-button/index.tsx
import { ReloadOutlined } from '@ant-design/icons';
import { S2_PREFIX_CLS, i18n } from '@antv/s2';
import React from 'react';
import './index.less';

interface ResetButtonProps {
  onClick?: (e: React.MouseEvent) => void;
}

const PRE_CLASS = `${S2_PREFIX_CLS}-reset-btn`;

export const ResetButton: React.FC<ResetButtonProps> = React.memo((props) => {
  const { onClick } = props;

  return (
    <span className={PRE_CLASS} onClick={onClick}>
      <ReloadOutlined className={`${PRE_CLASS}-icon`} />
      <span className={`${PRE_CLASS}-text`}>{i18n('重置')}</span>
    </span>
  );
});

ResetButton.displayName = 'ResetButton';
