// packages/s2-core/src/components/pagination/index.tsx
import React from 'react';
import { Pagination as AntDPagination } from 'antd';
import { isEmpty } from 'lodash';
import { i18n } from '@/common/i18n';
import { S2_PREFIX_CLS } from '@/common/constant/classnames';
import { Pagination } from '@/common/interface';

export interface S2PaginationProps {
  pagination: Pagination;
  current: number;
  total: number;
  pageSize?: number;
  setCurrent?: (current: number) => void;
  setPageSize?: (pageSize: number) => void;
}

export const S2Pagination: React.FC<S2PaginationProps> = ({
  pagination,
  current,
  total,
  pageSize,
  setCurrent,
  setPageSize,
}) => {
  // not show the pagination
  if (isEmpty(pagination)) {
    return null;
  }

  // only show the pagination when the pageSize > 5
  const showQuickJumper = total / pageSize > 5;
  const PRE_CLASS = `${S2_PREFIX_CLS}-pagination`;

  return (
    <div className={PRE_CLASS}>
      <AntDPagination
        defaultCurrent={1}
        current={current}
        total={total}
        pageSize={pageSize}
        showSizeChanger
        onShowSizeChange={(current, size) => {
          setPageSize(size);
        }}
        size={'small'}
        showQuickJumper={showQuickJumper}
        onChange={(page) => setCurrent(page)}
      />
      <span
        className={`${PRE_CLASS}-count`}
        title={`${i18n('共计')}${total}${i18n('条')}`}
      >
        {i18n('共计')}
        {total || ' - '}
        {i18n('条')}
      </span>
    </div>
  );
};

S2Pagination.displayName = 'S2Pagination';

// packages/s2-vue/src/components/pagination/index.vue
<script lang="ts">
import { computed, defineComponent } from 'vue';
import { S2_PREFIX_CLS } from '@antv/s2';
import { Pagination as AntDPagination } from 'ant-design-vue';
import { i18n } from '../../common/i18n';
import {
  DEFAULT_PAGE_NUMBER,
  DEFAULT_PAGE_SIZE,
} from '../../hooks/usePagination';

const PRE_CLASS = `${S2_PREFIX_CLS}-pagination`;

export default defineComponent({
  name: 's2-pagination',
  props: {
    current: {
      type: Number,
      default: DEFAULT_PAGE_NUMBER,
    },
    total: {
      type: Number,
      default: 0,
    },
    pageSize: {
      type: Number,
      default: DEFAULT_PAGE_SIZE,
    },
  },
  emits: ['change', 'showSizeChange'] as unknown as {
    change: (current: number) => void;
    showSizeChange: (size: number) => void;
  },
  setup: (props) => {
    // only show the pagination when the pageSize > 5
    const showQuickJumper = computed(() => {
      return props.total / props.pageSize > 5;
    });

    return {
      showQuickJumper,
      PRE_CLASS,
      i18n,
    };
  },
  components: {
    AntDPagination,
  },
});
</script>

<template>
  <div :class="PRE_CLASS">
    <AntDPagination
      :default-current="1"
      :current="current"
      :total="total"
      :pageSize="pageSize"
      :showSizeChanger="true"
      @showSizeChange="(_, size) => $emit('showSizeChange', size)"
      size="small"
      :showQuickJumper="showQuickJumper"
      @change="(current) => $emit('change', current)"
    />
    <span :class="`${PRE_CLASS}-count`">
      {{ i18n('共计') }} {{ total || ' - ' }} {{ i18n('条') }}
    </span>
  </div>
</template>
