// packages/s2-react/playground/components/Pagination/index.tsx
import { i18n } from '@antv/s2';
import { Pagination } from 'antd';
import { isEmpty } from 'lodash';
import React from 'react';
import { usePagination } from '../../../src/hooks';
import { usePlaygroundContext } from '../../context/playground.context';
import './index.less';

interface PlaygroundSheetPaginationProps {}

const PRE_CLASS = `sheet-pagination`;

export const PlaygroundSheetPagination: React.FC<
  PlaygroundSheetPaginationProps
> = () => {
  const context = usePlaygroundContext();
  const sheetInstance = context.ref?.current!;
  const pagination = usePagination(sheetInstance);

  if (isEmpty(pagination)) {
    return null;
  }

  const { total, pageSize } = pagination;
  // 大于 5页时展示快速跳转
  const showQuickJumper = total! / pageSize > 5;

  return (
    <div className={PRE_CLASS}>
      <Pagination
        size="small"
        defaultCurrent={1}
        showSizeChanger
        showQuickJumper={showQuickJumper}
        {...pagination}
      />
      <span
        className={`${PRE_CLASS}-count`}
        title={`${i18n('共计')}${total}${i18n('条')}`}
      >
        {i18n('共计')}
        {total || ' - '}
        {i18n('条')}
      </span>
    </div>
  );
};

PlaygroundSheetPagination.displayName = 'PlaygroundSheetPagination';

// packages/s2-vue/src/components/pagination/index.vue
<script lang="ts">
import { computed, defineComponent } from 'vue';
import { S2_PREFIX_CLS } from '@antv/s2';
import { Pagination as AntDPagination } from 'ant-design-vue';
import { i18n } from '@antv/s2';
import {
  DEFAULT_PAGE_NUMBER,
  DEFAULT_PAGE_SIZE,
} from '../../hooks/usePagination';

const PRE_CLASS = `${S2_PREFIX_CLS}-pagination`;

export default defineComponent({
  name: 's2-pagination',
  props: {
    current: {
      type: Number,
      default: DEFAULT_PAGE_NUMBER,
    },
    total: {
      type: Number,
      default: 0,
    },
    pageSize: {
      type: Number,
      default: DEFAULT_PAGE_SIZE,
    },
  },
  emits: ['change', 'showSizeChange'] as unknown as {
    change: (pagination: { current: number; pageSize: number }) => void;
    showSizeChange: (pagination: { current: number; pageSize: number }) => void;
  },
  setup: (props) => {
    // only show the pagination when the pageSize > 5
    const showQuickJumper = computed(() => {
      return props.total / props.pageSize > 5;
    });

    return {
      showQuickJumper,
      PRE_CLASS,
      i18n,
    };
  },
  components: {
    AntDPagination,
  },
});
</script>

<template>
  <div :class="PRE_CLASS">
    <AntDPagination
      :default-current="1"
      :current="current"
      :total="total"
      :pageSize="pageSize"
      :showSizeChanger="true"
      @showSizeChange="
        (current, pageSize) => $emit('showSizeChange', { current, pageSize })
      "
      size="small"
      :showQuickJumper="showQuickJumper"
      @change="(current, pageSize) => $emit('change', { current, pageSize })"
    />
    <span :class="`${PRE_CLASS}-count`">
      {{ i18n('共计') }} {{ total || ' - ' }} {{ i18n('条') }}
    </span>
  </div>
</template>
