// packages/s2-react/src/components/tooltip/components/detail.tsx
import React from 'react';
import { ListItem, TooltipDetailProps, TOOLTIP_PREFIX_CLS } from '@antv/s2';
import { Icon } from './icon';

export const TooltipDetail = (props: TooltipDetailProps) => {
  const { list = [] } = props;

  return (
    <div className={`${TOOLTIP_PREFIX_CLS}-detail-list`}>
      {list.map((listItem: ListItem, idx) => {
        const { name, value, icon } = listItem;

        return (
          <div
            key={`${value}-${idx}`}
            className={`${TOOLTIP_PREFIX_CLS}-detail-item`}
          >
            <span className={`${TOOLTIP_PREFIX_CLS}-detail-item-key`}>
              {name}
            </span>
            <span
              className={`${TOOLTIP_PREFIX_CLS}-detail-item-val ${TOOLTIP_PREFIX_CLS}-highlight`}
            >
              {icon ? <Icon icon={icon} width={8} height={7} /> : null} {value}
            </span>
          </div>
        );
      })}
    </div>
  );
};

// packages/s2-vue/src/components/tooltip/components/detail.vue
<script lang="ts">
import {
  type ListItem,
  type TooltipDetailProps,
  TOOLTIP_PREFIX_CLS,
} from '@antv/s2';
import { defineComponent } from 'vue';
import type { GetInitProps } from '../../../interface';

export default defineComponent({
  name: 'TooltipDetail',
  props: ['list'] as unknown as GetInitProps<TooltipDetailProps>,
  setup() {
    return {
      TOOLTIP_PREFIX_CLS,
    };
  },
});
</script>

<template>
  <div
    v-for="(item, index) in list"
    :key="`${item.value}-${index}`"
    :class="`${TOOLTIP_PREFIX_CLS}-detail-list`"
  >
    <div :class="`${TOOLTIP_PREFIX_CLS}-detail-item`">
      <span :class="`${TOOLTIP_PREFIX_CLS}-detail-item-key`">
        {{ item.name }}
      </span>
      <span
        :class="`${TOOLTIP_PREFIX_CLS}-detail-item-val ${TOOLTIP_PREFIX_CLS}-highlight`"
      >
        {{ item.value }}
      </span>
    </div>
  </div>
</template>

<style lang="less"></style>
