// packages/s2-core/src/ui/tooltip/components/summary.tsx
import React from 'react';
import { size, reduce } from 'lodash';
import { SummaryProps } from '@/common/interface';
import { i18n } from '@/common/i18n';
import { TOOLTIP_PREFIX_CLS } from '@/common/constant/tooltip';

export const TooltipSummary: React.FC<SummaryProps> = React.memo((props) => {
  const { summaries = [] } = props;

  const renderSelected = () => {
    const count = reduce(
      summaries,
      (pre, next) => pre + size(next?.selectedData),
      0,
    );
    return (
      <div className={`${TOOLTIP_PREFIX_CLS}-summary-item`}>
        <span className={`${TOOLTIP_PREFIX_CLS}-bold`}>
          {count} {i18n('项')}
        </span>{' '}
        {i18n('已选择')}
      </div>
    );
  };

  const renderSummary = () => {
    return summaries?.map((item) => {
      const { name = '', value } = item || {};
      if (!name && !value) {
        return;
      }

      return (
        <div
          key={`${name}-${value}`}
          className={`${TOOLTIP_PREFIX_CLS}-summary-item`}
        >
          <span className={`${TOOLTIP_PREFIX_CLS}-summary-key`}>
            {name}（{i18n('总和')})
          </span>
          <span
            className={`${TOOLTIP_PREFIX_CLS}-summary-val ${TOOLTIP_PREFIX_CLS}-bold`}
          >
            {value}
          </span>
        </div>
      );
    });
  };

  return (
    <div className={`${TOOLTIP_PREFIX_CLS}-summary`}>
      {renderSelected()}
      {renderSummary()}
    </div>
  );
});

// packages/s2-vue/src/components/tooltip/components/summary.vue
<script lang="ts">
import { size, reduce } from 'lodash';
import { i18n, type SummaryProps, TOOLTIP_PREFIX_CLS } from '@antv/s2';
import { computed, defineComponent } from 'vue';
import type { GetInitProps } from '../../../interface';

export default defineComponent({
  name: 'TooltipSummary',
  props: ['summaries'] as unknown as GetInitProps<SummaryProps>,
  setup(props) {
    const count = computed(() =>
      reduce(props.summaries, (pre, next) => pre + size(next?.selectedData), 0),
    );

    return {
      count: count.value,
      i18n,
      TOOLTIP_PREFIX_CLS,
    };
  },
  components: {},
});
</script>

<template>
  <div :class="`${TOOLTIP_PREFIX_CLS}-summary`">
    <div :class="`${TOOLTIP_PREFIX_CLS}-summary-item`">
      <span :class="`${TOOLTIP_PREFIX_CLS}-selected`">
        {{ count }} {{ i18n('项') }}
      </span>
      {{ i18n('已选择') }}
    </div>
    <div
      v-for="summary in summaries"
      :key="`${summary.name}-${summary.value}`"
      :class="`${TOOLTIP_PREFIX_CLS}-summary-item`"
    >
      <span :class="`${TOOLTIP_PREFIX_CLS}-summary-key`">
        {{ summary.name }} {{ i18n('总和') }}
      </span>
      <span
        :class="`${TOOLTIP_PREFIX_CLS}-summary-val ${TOOLTIP_PREFIX_CLS}-bold`"
      >
        {{ summary.value }}
      </span>
    </div>
  </div>
</template>

<style lang="less"></style>
